"undefined"===typeof Worker||"undefined"!==typeof location&&"file:"===location.protocol?"undefined"!==typeof global&&"undefined"!==typeof require?this.LZMA=function(a){return require(a||"./lzma_worker-min.js").LZMA}:"undefined"!==typeof window&&window.document?function(){function a(a){var b;e(a);return b={compress:function(a,e,f,p){d.LZMA_WORKER?d.LZMA_WORKER.compress(a,e,f,p):setTimeout(function(){b.compress(a,e,f,p)},50)},decompress:function(a,e,f){d.LZMA_WORKER?d.LZMA_WORKER.decompress(a,e,f):
setTimeout(function(){b.decompress(a,e,f)},50)}}}var b=this,d,e=function(d){var e=document.createElement("script");e.type="text/javascript";e.src=d;e.onload=function(){b.LZMA=a};document.getElementsByTagName("head")[0].appendChild(e)};"undefined"!==typeof window?d=window:global&&(d=global);b.LZMA=a}():console.log("Can't load the worker. Sorry."):this.LZMA=function(a){var b={},d=new Worker(a||"./lzma_worker-min.js");d.onmessage=function(a){if(3===a.data.action){if(b[a.data.cbn]&&"function"===typeof b[a.data.cbn].on_progress)b[a.data.cbn].on_progress(a.data.result)}else b[a.data.cbn]&&
"function"===typeof b[a.data.cbn].on_finish&&(b[a.data.cbn].on_finish(a.data.result),delete b[a.data.cbn])};d.onerror=function(a){throw Error(a.message+" ("+a.filename+":"+a.lineno+")");};return function(){function a(e,g,h,k,l){var p;do p=Math.floor(1E7*Math.random());while("undefined"!==typeof b[p]);b[p]={on_finish:k,on_progress:l};d.postMessage({action:e,cbn:p,data:g,mode:h})}return{compress:function(b,d,h,k){a(1,b,d,h,k)},decompress:function(b,d,h){a(2,b,!1,d,h)}}}()};
var MO=new function(){this.version="0.3.0";this.info={};this.Lang=new function(){return this};this.Stream=new function(){return this};this.Core=new function(){return this};this.Gui=new function(){return this};this.Dui=new function(){return this};return this};MO.initialize=function(){var a=0,b;for(b in this){var d=this[b];d&&d.constructor==Function&&(d.__name=b);a++}this.info.count=a};MO.release=function(){};MO.RSingleton=function(){this._singleton=!0;return this};
MO.TEnum=function(){this.toDisplay=MO.TEnum_toDisplay;this.toValue=MO.TEnum_toValue;return this};MO.TEnum_toDisplay=function(a,b){for(var d in this){var e=this[d];if(e.constructor!=Function&&e==a)return d}return b};MO.TEnum_toValue=function(a,b){var d=a.toLowerCase(),e;for(e in this)if(this[e].constructor!=Function&&e.toLowerCase()==d)return this[e];return b};MO.ELogger=new function(){MO.TEnum.call(this);this.Unknown=0;this.Debug=1;this.Info=2;this.Warn=3;this.Error=4;this.Fatal=5;return this};
MO.EPlatform=new function(){MO.TEnum.call(this);this.Unknown=0;this.Pc=1;this.Mobile=2;return this};MO.EProcess=new function(){MO.TEnum.call(this);this.Unknown=0;this.Debug=1;this.Release=2;return this};MO.RRuntime=function(){var a=MO.RSingleton.call(this);a._processCd=MO.EProcess.Release;a._platformCd=MO.EPlatform.Pc;return a};MO.RRuntime.prototype.isDebug=function(){return this._processCd==MO.EProcess.Debug};MO.RRuntime.prototype.isRelease=function(){return this._processCd==MO.EProcess.Release};
MO.RRuntime.prototype.processCd=function(){return this._processCd};MO.RRuntime.prototype.setProcessCd=function(a){this._processCd=a};MO.RRuntime.prototype.isPlatformPc=function(){return this._platformCd==MO.EPlatform.Pc};MO.RRuntime.prototype.isPlatformMobile=function(){return this._platformCd==MO.EPlatform.Mobile};MO.RRuntime.prototype.platformCd=function(){return this._platformCd};MO.RRuntime.prototype.setPlatformCd=function(a){this._platformCd=a};MO.RRuntime.prototype.empty=function(){};
MO.RRuntime.prototype.nvl=function(a,b){return null!=a?a:b};MO.RRuntime.prototype.subString=function(a,b,d){if(null==a)return a;var e=0;if(null!=b){var f=a.indexOf(b);-1!=f&&(e=f+b.length)}b=a.length;null!=d&&(f=a.indexOf(d,length),-1!=f&&(b=f));return e>=b?"":a.substring(e,b)};MO.RRuntime.prototype.className=function(a){return a&&("function"==typeof a||(a=a.constructor))?this.subString(a.toString(),"function ","("):null};MO.RRuntime.prototype.sortComparerAsc=function(a,b,d){return a>b?1:a<b?-1:0};
MO.RRuntime.prototype.sortComparerDesc=function(a,b,d){return a>b?-1:a<b?1:0};MO.RRuntime.prototype.pairSortMid=function(a,b,d,e,f,g){var h=a[d];if(b)var k=b[d];for(;d<e;){for(;d<e&&0<=f(a[e],h,g);)e--;a[d]=a[e];for(b&&(b[d]=b[e]);d<e&&0>=f(a[d],h,g);)d++;a[e]=a[d];b&&(b[e]=b[d])}a[d]=h;b&&(b[d]=k);return d};MO.RRuntime.prototype.pairSortSub=function(a,b,d,e,f,g){if(d<e){var h=this.pairSortMid(a,b,d,e,f,g);this.pairSortSub(a,b,d,h-1,f,g);this.pairSortSub(a,b,h+1,e,f,g)}};
MO.RRuntime.prototype.pairSort=function(a,b,d,e,f,g){this.pairSortSub(a,b,d,d+e-1,MO.Runtime.nvl(f,this.sortComparerAsc),g)};MO.Runtime=new MO.RRuntime;MO.TAttributes=function(){MO.TDictionary.call(this);this.joinValue=MO.TAttributes_joinValue;this.join=MO.TAttributes_join;this.split=MO.TAttributes_split;this.pack=MO.TAttributes_pack;this.unpack=MO.TAttributes_unpack;this.dump=MO.TAttributes_dump;return this};
MO.TAttributes_joinValue=function(a){for(var b=new MO.TString,d=this._count,e=0;e<d;e++)0<e&&b.append(a),b.append(this._values[e]);return b.flush()};MO.TAttributes_join=function(a,b){var d=new MO.TString;a||(a="=");b||(b=",");for(var e=this._count,f=0;f<e;f++)0<f&&d.append(b),d.append(this._names[f]),d.append(a),d.append(this._values[f]);return d.flush()};
MO.TAttributes_split=function(a,b,d){a=a.split(d);d=a.length;for(var e=0;e<d;e++){var f=a[e];if(f.length){var g=f.split(b);2==g.length?this.set(MO.Lang.String.trim(g[0]),MO.Lang.String.trim(g[1])):this.set(MO.Lang.String.trim(f),"")}}};MO.TAttributes_pack=function(){for(var a=new MO.TString,b=this._count,d=this._names,e=this._values,f=0;f<b;f++){var g=d[f],h=e[f],k=g.length;a.append(k.toString().length,k,g);null!=h?(h+="",g=h.length,a.append(g.toString().length,g,h)):a.append("0")}return a.flush()};
MO.TAttributes_unpack=function(a){for(var b=this.count=0,d=a.length;b<d;){var e=parseInt(a.substr(b++,1)),f=parseInt(a.substr(b,e)),g=a.substr(b+e,f),b=b+(e+f),e=parseInt(a.substr(b++,1)),h=null;0<e&&(f=parseInt(a.substr(b,e)),h=a.substr(b+e,f),b+=e+f);this.set(g,h)}};MO.TAttributes_dump=function(){var a=new MO.TString,b=this._count;a.append(MO.Runtime.className(this)," : ",b);if(0<b){var d=this._names,e=this._values;a.append(" (");for(var f=0;f<b;f++)0<f&&a.append(", "),a.append(d[f],"=",e[f]);a.append(")")}return a.flush()};
MO.TDictionary=function(){MO.TMap.call(this);this.sortByName=MO.TDictionary_sortByName;this.joinName=MO.TDictionary_joinName;this.dump=MO.TDictionary_dump;return this};MO.TDictionary_sortByName=function(a,b){MO.Runtime.pairSort(this._names,this._values,0,this._count,a,b);this.rebuild()};MO.TDictionary_joinName=function(a){for(var b=new MO.TString,d=this._count,e=0;e<d;e++)0<e&&b.append(a),b.append(this._names[e]);return b.flush()};
MO.TDictionary_dump=function(){var a=new MO.TString,b=this._count;a.append(MO.Runtime.className(this),": ",b);if(0<b){var d=this._names,e=this._values;a.append(" {\n");for(var f=0;f<b;f++)a.append("   ",d[f],"=[",e[f],"]\n");a.append("}")}return a.flush()};
MO.TMap=function(){this._count=0;this._table={};this._names=[];this._values=[];this.isEmpty=MO.TMap_isEmpty;this.count=MO.TMap_count;this.contains=MO.TMap_contains;this.containsValue=MO.TMap_containsValue;this.indexOf=MO.TMap_indexOf;this.indexOfValue=MO.TMap_indexOfValue;this.first=MO.TMap_first;this.last=MO.TMap_last;this.nameAt=MO.TMap_nameAt;this.name=MO.TMap_name;this.at=this.valueAt=MO.TMap_valueAt;this.value=MO.TMap_value;this.setValueAt=MO.TMap_setValueAt;this.setValue=MO.TMap_setValue;this.get=
MO.TMap_get;this.set=MO.TMap_set;this.assign=MO.TMap_assign;this.append=MO.TMap_append;this.insert=MO.TMap_insert;this.remove=MO.TMap_remove;this.removeName=MO.TMap_removeName;this.removeValue=MO.TMap_removeValue;this.rebuild=MO.TMap_rebuild;this.clear=MO.TMap_clear;this.toString=MO.TMap_toString;this.dispose=MO.TMap_dispose;this.dump=MO.TMap_dump;return this};MO.TMap_isEmpty=function(){return 0==this._count};MO.TMap_count=function(){return this._count};
MO.TMap_contains=function(a){return null!=a&&null!=this._table[a.toString().toLowerCase()]?!0:!1};MO.TMap_containsValue=function(a){return-1!=this.indexOfValue(a)};MO.TMap_indexOf=function(a){return null!=a&&(a=this._table[a.toString().toLowerCase()],null!=a)?a:-1};MO.TMap_indexOfValue=function(a){var b=this._count;if(0<b)for(var d=this._values,e=0;e<b;e++)if(d[e]==a)return e;return-1};MO.TMap_first=function(){return 0<this._count?this._values[0]:null};
MO.TMap_last=function(){return 0<this._count?this._values[this._count-1]:null};MO.TMap_nameAt=function(a){return this._names[a]};MO.TMap_name=function(a){return 0<=a&&a<this._count?this._names[a]:null};MO.TMap_valueAt=function(a){return this._values[a]};MO.TMap_value=function(a){return 0<=a&&a<this._count?this._values[a]:null};MO.TMap_setValueAt=function(a,b){this._values[a]=b};MO.TMap_setValue=function(a,b){0<=a&&a<this._count&&(this._values[a]=b)};
MO.TMap_get=function(a,b){if(null!=a){var d=this._table[a.toString().toLowerCase()];if(null!=d)return this._values[d]}return b};MO.TMap_set=function(a,b){if(null!=a){var d=a.toString().toLowerCase(),e=this._table[d];if(null==e||e>=this._count)e=this._count++,this._names[e]=a,this._table[d]=e;this._values[e]=b}};MO.TMap_assign=function(a){this.clear();this.append(a)};MO.TMap_append=function(a){if(a)for(var b=a.count(),d=0;d<b;d++){var e=a.nameAt(d),f=a.valueAt(d);this.set(e,f)}};
MO.TMap_insert=function(a,b,d){var e=this._count;if(0<=a&&a<=e){for(var f=this._names,g=this._values;e>a;e--)f[e]=f[e-1],g[e]=g[e-1];f[a]=b;g[a]=d;this._count++;this.rebuild()}};MO.TMap_remove=function(a){var b=null,d=this._count;if(0<=a&&a<d){for(var e=this._names,f=this._values,b=f[a];a<d;a++)e[a]=e[a+1],f[a]=f[a+1];this._count--;this.rebuild()}return b};MO.TMap_removeName=function(a){a=this.indexOf(a);return-1!=a?this.remove(a):null};
MO.TMap_removeValue=function(a){for(var b=0,d=this._count,e=this._names,f=this._values,g=0;g<d;g++){var h=f[g];h!=a&&(b!=g&&(e[b]=e[g],f[b]=h),b++)}this._count=b;this.rebuild()};MO.TMap_rebuild=function(){var a=this._table,b;for(b in a)delete a[b];b=this._count;for(var d=this._names,e=0;e<b;e++){var f=d[e].toLowerCase();a[f]=e}};MO.TMap_clear=function(){this._count=0;var a=this._table,b;for(b in a)delete a[b]};MO.TMap_toString=function(){return this.dump().toString()};
MO.TMap_dispose=function(a){var b=this._count,d=this._table;if(d){for(var e in d)d[e]=null;this._table=null}if(e=this._names){for(d=0;d<b;d++)e[d]=null;this._names=null}if(e=this._values){for(d=0;d<b;d++)a&&MO.Lang.Object.dispose(e[d]),e[d]=null;this._values=null}this._count=0};MO.TMap_dump=function(){var a=new MO.TString,b=this._count;a.appendLine(MO.Runtime.className(this),": ",b);if(0<b){var d=this._names,e=this._values;a.append(" {");for(var f=0;f<b;f++)a.appendLine(d[f],"=[",e[f],"]");a.append("}")}return a.flush()};
MO.TObjects=function(){this._count=0;this._items=[];this.isEmpty=MO.TObjects_isEmpty;this.count=MO.TObjects_count;this.items=MO.TObjects_items;this.contains=MO.TObjects_contains;this.indexOf=MO.TObjects_indexOf;this.first=MO.TObjects_first;this.last=MO.TObjects_last;this.at=this.getAt=MO.TObjects_getAt;this.get=MO.TObjects_get;this.setAt=MO.TObjects_setAt;this.set=MO.TObjects_set;this.assign=MO.TObjects_assign;this.append=MO.TObjects_append;this.insert=MO.TObjects_insert;this.shift=MO.TObjects_shift;
this.unshift=MO.TObjects_unshift;this.pop=MO.TObjects_pop;this.push=MO.TObjects_push;this.pushUnique=MO.TObjects_pushUnique;this.swap=MO.TObjects_swap;this.sort=MO.TObjects_sort;this.erase=MO.TObjects_erase;this.remove=MO.TObjects_remove;this.clear=MO.TObjects_clear;this.dispose=MO.TObjects_dispose;this.dump=MO.TObjects_dump;return this};MO.TObjects_isEmpty=function(){return 0==this._count};MO.TObjects_count=function(){return this._count};MO.TObjects_items=function(){return this._items};
MO.TObjects_contains=function(a){return-1!=this.indexOf(a)};MO.TObjects_indexOf=function(a){for(var b=this._count,d=this._items,e=0;e<b;e++)if(d[e]==a)return e;return-1};MO.TObjects_first=function(){return this._count?this._items[0]:null};MO.TObjects_last=function(){return this._count?this._items[this._count-1]:null};MO.TObjects_getAt=function(a){return this._items[a]};MO.TObjects_get=function(a){return 0<=a&&a<this._count?this._items[a]:null};MO.TObjects_setAt=function(a,b){this._items[a]=b};
MO.TObjects_set=function(a,b){var d=this._items;0<=a&&a<this._count&&(d[a]=b)};MO.TObjects_assign=function(a){var b=this._items,d=this._count=a.count();a=a.items();for(var e=0;e<d;e++)b[e]=a[e]};MO.TObjects_append=function(a){for(var b=a.count(),d=0;d<b;d++)this.push(a.at(d))};MO.TObjects_insert=function(a,b){var d=this._count,e=this._items;if(0<=a&&a<=d){for(;d>a;d--)e[d]=e[d-1];e[a]=b;this._count++}};MO.TObjects_shift=function(){return this.erase(0)};
MO.TObjects_unshift=function(a){return this.insert(0,a)};MO.TObjects_pop=function(){var a=null;this._count&&(a=this._items[--this._count]);return a};MO.TObjects_push=function(a){var b=this._count++;this._items[b]=a;return b};MO.TObjects_pushUnique=function(a){this.indexOf(a);-1==a&&this.push(a)};MO.TObjects_swap=function(a,b){var d=this._count;if(0<=a&&a<d&&0<=b&&b<d&&a!=b){var d=this._items,e=d[a];d[a]=d[b];d[b]=e}};
MO.TObjects_sort=function(a){var b=this._items;b.length!=this._count&&(b.length=this._count);b.sort(a)};MO.TObjects_erase=function(a){var b=null;if(0<=a&&a<this._count){for(var d=this._items,b=d[a],e=--this._count;a<e;a++)d[a]=d[a+1];d[e]=null}return b};MO.TObjects_remove=function(a){var b=this._count;if(b){for(var d=0,e=this._items,f=d;f<b;f++)e[f]!=a&&(e[d++]=e[f]);for(f=d;f<b;f++)e[f]=null;this._count=d}return a};MO.TObjects_clear=function(){this._count=0};
MO.TObjects_dispose=function(){var a=this._items,b;for(b in a)a[b]=null;this._count=0;this._items=null};MO.TObjects_dump=function(){var a=othis._count,b=new MO.TString;b.append(MO.Runtime.className(this),":",a);if(a)for(var d=0;d<a;d++)b.append(" [",this._items[d],"]");return b.flush()};
MO.TString=function(){this._count=0;this._memory=[];this.isEmpty=MO.TString_isEmpty;this.assign=MO.TString_assign;this.append=MO.TString_append;this.appendIf=MO.TString_appendIf;this.appendArray=MO.TString_appendArray;this.appendLine=MO.TString_appendLine;this.appendRepeat=MO.TString_appendRepeat;this.push=MO.TString_push;this.clear=MO.TString_clear;this.toString=MO.TString_toString;this.flush=MO.TString_flush;this.dispose=MO.TString_dispose;this.dump=MO.TString_dump;return this};
MO.TString_isEmpty=function(){return 0==this._count};MO.TString_assign=function(){this.clear();this.appendArray(arguments,0,arguments.length)};MO.TString_append=function(){this.appendArray(arguments,0,arguments.length)};MO.TString_appendIf=function(a){a&&this.appendArray(arguments,1,arguments.length-1)};MO.TString_appendArray=function(a,b,d){for(var e=this._memory,f=0;f<d;f++){var g=a[b++];null!=g&&(e[this._count++]=g)}};
MO.TString_appendRepeat=function(a,b){for(var d=this._memory,e=0;e<b;e++)d[this._count++]=a};MO.TString_appendLine=function(){this.appendArray(arguments,0,arguments.length);this._memory[this._count++]="\r\n"};MO.TString_push=function(){this.appendArray(arguments,0,arguments.length)};MO.TString_clear=function(){this._count=0};MO.TString_toString=function(){var a=this._memory;a.length!=this._count&&(a=a.slice(0,this._count));return a.join("")};
MO.TString_flush=function(){var a=this.toString();this.dispose();return a};MO.TString_dispose=function(){this._count=0;var a=this._memory;if(a){for(var b=a.length,d=0;d<b;d++)a[d]=null;this._memory=null}};MO.TString_dump=function(){var a=this.toString();return MO.Runtime.className(o)+":"+a.length+"["+a+"]"};MO.RAssert=function(){var a=MO.RSingleton.call(this);a.debugBegin=MO.Runtime.empty;a.debug=MO.Runtime.empty;a.debugEnd=MO.Runtime.empty;return a};
MO.RAssert.prototype.isTrue=function(a){if(!a)throw Error("Assert ture failure.");};MO.RAssert.prototype.isFalse=function(a){if(a)throw Error("Assert false failure.");};MO.RAssert.prototype.debugTrue=function(a){if(!a)throw Error("Assert true failure.");};MO.RAssert.prototype.debugFalse=function(a){if(a)throw Error("Assert false failure.");};MO.RAssert.prototype.debugNull=function(a){if(null!=a)throw Error("Assert null failure.");};
MO.RAssert.prototype.debugNotNull=function(a){if(null==a)throw Error("Assert not null failure.");};MO.RAssert.prototype.debugEmpty=function(a){if(null!=a&&0!=a.length)throw Error("Assert empty failure.");};MO.RAssert.prototype.debugNotEmpty=function(a){if(null==a)throw Error("Assert not empty failure, value is null.");if(0==a.length)throw Error("Assert not empty failure, value length is empty.");};MO.Assert=new MO.RAssert;
MO.AAnnotation=function(a){this._annotationCd=null;this._ordered=this._duplicate=this._inherit=!1;this._name=a;this.annotationCd=MO.AAnnotation_annotationCd;this.isInherit=MO.AAnnotation_isInherit;this.isDuplicate=MO.AAnnotation_isDuplicate;this.isOrdered=MO.AAnnotation_isOrdered;this.name=MO.AAnnotation_name;this.code=MO.AAnnotation_code;this.value=MO.AAnnotation_value;return this};MO.AAnnotation_annotationCd=function(){return this._annotationCd};MO.AAnnotation_isInherit=function(){return this._inherit};
MO.AAnnotation_isDuplicate=function(){return this._duplicate};MO.AAnnotation_isOrdered=function(){return this._ordered};MO.AAnnotation_name=function(){return this._name};MO.AAnnotation_code=function(){return this._name};MO.AAnnotation_value=function(){return null};MO.AGetSet=function(a,b){MO.ASource.call(this,a,MO.ESource.GetSet,b);this.build=MO.AGetSet_build;return this};
MO.AGetSet_build=function(a,b){var d=this._code;b[d]=MO.Method.makePropertyGet(this._name,d);d="set"+this._linker;b[d]=MO.Method.makePropertySet(this._name,d)};MO.AGetter=function(a,b){MO.ASource.call(this,a,MO.ESource.Get,b);this._linker=b;this.build=MO.AGetter_build;return this};MO.AGetter_build=function(a,b){var d=this._linker?this._linker:this._code;b[d]=MO.Method.makePropertyGet(this._name,d)};MO.ASetter=function(a,b){MO.ASource.call(this,a,MO.ESource.Set,b);this.build=MO.ASetter_build;return this};
MO.ASetter_build=function(a,b){var d="set"+this._linker;b[d]=MO.Method.makePropertySet(this._name,d)};MO.ASource=function(a,b,d){MO.AAnnotation.call(this,a);this._inherit=!1;this._annotationCd=MO.EAnnotation.Source;this._typeCd=b;this._linker=this._code=null;this.build=MO.ASource_build;this.toString=MO.ASource_toString;a=this._name;MO.Lang.String.startsWith(a,"_")&&(a=a.substring(1));this._code=a;this._linker=null==d?MO.Lang.String.firstUpper(a):d;return this};MO.ASource_build=function(){};
MO.ASource_toString=function(){return"<"+this._annotationCd+",linker="+this._linker+">"};MO.EAnnotation=new function(){this.Constructor="constructor";this.Dispose="dispose";this.Source="source";this.Property="property";this.Persistence="persistence";this.Event="enum";this.Event="event";this.Linker="linker";this.Style="style";this.StyleIcon="icon";return this};
MO.EDataType=new function(){this.Unknown=0;this.Int8=1;this.Int16=2;this.Int32=3;this.Int64=4;this.Uint8=5;this.Uint16=6;this.Uint32=7;this.Uint64=8;this.Float16=9;this.Float32=this.Float=10;this.Float64=this.Double=11;this.String=12;this.Struct=13;this.Object=14;this.Array=15;this.Objects=16;this.Dictionary=17;return this};MO.EEndian=new function(){this.Big=0;this.Little=1;return this};MO.ESource=new function(){this.Get="get";this.Set="set";this.GetSet="getset";this.Listener="listener";return this};
MO.SLogger=function(){this.message=null;return this};
MO.TClass=function(){this.__disposed=!0;this._unused=null;this._annotations={};this._attributes={};this.instance=this.clazz=this.base=this.parent=this.name=null;this._abstract=!1;this.styles=[];this.instances=[];this.register=MO.TClass_register;this.assign=MO.TClass_assign;this.annotations=MO.TClass_annotations;this.annotation=MO.TClass_annotation;this.annotationFind=MO.TClass_annotationFind;this.attributeFind=MO.TClass_attributeFind;this.style=MO.TClass_style;this.build=MO.TClass_build;this.newInstance=
MO.TClass_newInstance;this.free=MO.TClass_free;this.alloc=MO.TClass_alloc;return this};
MO.TClass_register=function(a){var b=a.annotationCd(),d=a.isOrdered(),e=a.name(),f=a.code();if(!b||!f)throw new MO.TError(this,"Unknown annotation. (class={1}, annotation={2}, name={3}, code={4})",MO.Class.dump(this),a,e,f);var g=this._annotations[b];g||(g=d?new MO.TObjects:{},this._annotations[b]=g);if(!a._duplicate&&g[f])throw new MO.TError(this,"Duplicate annotation. (class={1}, annotation={2}, name={3}, code={4}, value={5})",MO.Class.dump(this),a,e,f,a.toString());d?g.push(a):g[f]=a;this._attributes[e]=
a};MO.TClass_assign=function(a){for(var b in a._annotations){var d=a._annotations[b],e=this._annotations[b];e||(e=this._annotations[b]=new d.constructor);if(d.constructor==MO.TObjects)e.append(d);else for(var f in d){var g=d[f];if(!g.isDuplicate()&&e[f])throw new MO.TError(this,"Duplicate annotation. (annotation={1}, {2}.{3}={4}.{5}, source={6})",b,this.name,f,a.name,f,g.toString());g._inherit&&(e[f]=g)}}for(f in a._attributes)a._attributes[f].construct!=Function&&(this._attributes[f]=a._attributes[f])};
MO.TClass_annotations=function(a){var b=this._annotations[a];b||MO.Logger.fatal(this,null,"Can't find annotations. (annotation={1}, class={2})",a,this.name);return b};MO.TClass_annotation=function(a,b){var d=null,e=this._annotations[a];e&&(d=e[b]);d||MO.Logger.fatal(this,null,"Can't find annotation. (annotation={1}, name={2}, class={3})",a,b,this.name);return d};MO.TClass_annotationFind=function(a){for(var b in this._annotations){var d=this._annotations[b];if(d&&(d=d[a],null!=d&&d.constructor!=Function))return d}return null};
MO.TClass_attributeFind=function(a){return(a=this._attributes[a])&&a.constructor!=Function?a:null};MO.TClass_style=function(a){if(this.styles[a])return this.styles[a];for(var b=null,d=this;d;){var e=d._annotations[MO.EAnnotation.Style];if(e&&(b=e[a]))break;d=d.parent}b||MO.Logger.fatal(this,null,"No register style annotation. (name={1}, linker={2}, class={3})",this.name+"_"+a,this.liner,this.name);b=d.name+"_"+b.style();return this.styles[a]=b};
MO.TClass_build=function(){var a=this.instance,b;for(b in a){var d=a[b];if(null!=d&&d.constructor==Function&&d.__virtual){this._abstract=!0;break}}if(d=this._annotations[MO.EAnnotation.Property])for(b in d)d[b].build(a);if(d=this._annotations[MO.EAnnotation.Source])for(b in d)d[b].build(this,a)};
MO.TClass_newInstance=function(){var a=this.alloc();if(!a){if(this._abstract){var a=new MO.TString,b;for(b in this.instance){var d=this.instance[b];MO.Method.isVirtual(d)&&(a.isEmpty()||a.append(","),a.append(d._name))}throw new MO.TError(this,"Abstract Class can't be create.(name={1})\n[{2}]",this.name,a);}var e=this.instance;if(!e)return MO.Logger.fatal(this,null,"Class instance is empty. (name={1})",this.name);a=new e.constructor;for(b in e){d=e[b];if(null!=d){if("__base"==b||"__inherits"==b){a[b]=
e[b];continue}MO.Class.isBase(d)||(d=MO.Lang.Object.clone(d))}a[b]=d}a.__class=this;a.construct&&a.construct()}return a};MO.TClass_alloc=function(){var a=this._unused;a&&(this._unused=a.cnext,a.cnext=null,a._using=!0);return a};MO.TClass_free=function(a){if(a._using){a.cnext=this._unused;this._unused=a;a._using=!1;for(var b in a){var d=a[b];if(d&&!RClass.isBase(d))if(d._class)this.free(d);else if(this.isClass(d,Array))for(var e=0;e<d.length;e++){var f=d[e];f._class&&this.free(f)}}}};
MO.TClassBase=function(){this.__disposed=!0;return this};
MO.TDate=function(a){this.date=a?a:new Date;this.ms=this.second=this.minute=this.hour=this.day=this.month=this.year=null;this.equals=MO.TDate_equals;this.isBefore=MO.TDate_isBefore;this.isAfter=MO.TDate_isAfter;this.monthDays=MO.TDate_monthDays;this.monthWeekDay=MO.TDate_monthWeekDay;this.weekDay=MO.TDate_weekDay;this.totalSecond=MO.TDate_totalSecond;this.daySecond=MO.TDate_daySecond;this.assign=MO.TDate_assign;this.refresh=MO.TDate_refresh;this.setYear=MO.TDate_setYear;this.setMonth=MO.TDate_setMonth;
this.setDay=MO.TDate_setDay;this.setHour=MO.TDate_setHour;this.setMinute=MO.TDate_setMinute;this.setSecond=MO.TDate_setSecond;this.setDate=MO.TDate_setDate;this.setNow=MO.TDate_setNow;this.addYear=MO.TDate_addYear;this.addMonth=MO.TDate_addMonth;this.addDay=MO.TDate_addDay;this.addHour=MO.TDate_addHour;this.addMinute=MO.TDate_addMinute;this.addSecond=MO.TDate_addSecond;this.add=MO.TDate_add;this.truncDay=MO.TDate_truncDay;this.truncHour=MO.TDate_truncHour;this.truncMinute=MO.TDate_truncMinute;this.truncSecond=
MO.TDate_truncSecond;this.trunc=MO.TDate_trunc;this.get=MO.TDate_get;this.set=MO.TDate_set;this.parse=MO.TDate_parse;this.parseAuto=MO.TDate_parseAuto;this.format=MO.TDate_format;this.clone=MO.TDate_clone;this.dump=MO.TDate_dump;this.refresh();return this};MO.TDate_equals=function(a){return this.date.getTime()==a.date.getTime()};MO.TDate_isBefore=function(a){return this.date.getTime()<a.date.getTime()};MO.TDate_isAfter=function(a){return this.date.getTime()>a.date.getTime()};
MO.TDate_monthDays=function(){return RDate.monthDays(this.year,this.month)};MO.TDate_monthWeekDay=function(){return(8-(this.day-this.weekDay())%7)%7};MO.TDate_assign=function(a){this.date.setTime(a.date.getTime());this.refresh()};MO.TDate_refresh=function(){var a=this.date;a&&(this.year=a.getFullYear(),this.month=a.getMonth()+1,this.day=a.getDate(),this.hour=a.getHours(),this.minute=a.getMinutes(),this.second=a.getSeconds(),this.ms=a.getMilliseconds())};MO.TDate_weekDay=function(){return this.date.getDay()};
MO.TDate_totalSecond=function(){return parseInt(this.date.getTime()/1E3)};MO.TDate_daySecond=function(){return 3600*this.hour+60*this.minute+this.second};MO.TDate_setYear=function(a){this.date.setFullYear(a);this.refresh()};MO.TDate_setMonth=function(a){this.date.setMonth(parseInt(a,10)-1);this.refresh()};MO.TDate_setDay=function(a){this.date.setDate(a);this.refresh()};MO.TDate_setHour=function(a){this.date.setHours(a);this.refresh()};MO.TDate_setMinute=function(a){this.date.setMinutes(a);this.refresh()};
MO.TDate_setSecond=function(a){this.date.setSeconds(a);this.refresh()};MO.TDate_setDate=function(a){this.date=a;this.refresh()};MO.TDate_setNow=function(){this.date=new Date;this.refresh()};MO.TDate_addYear=function(a){var b=this.date.getFullYear();this.date.setFullYear(b+MO.Lang.Integer.nvl(a,1));this.refresh()};MO.TDate_addMonth=function(a){var b=this.date.getMonth();this.date.setMonth(b+MO.Lang.Integer.nvl(a,1));this.refresh()};
MO.TDate_addDay=function(a){a=this.date.getTime()+864E5*MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};MO.TDate_addHour=function(a){a=this.date.getTime()+36E5*MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};MO.TDate_addMinute=function(a){a=this.date.getTime()+6E4*MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};MO.TDate_addSecond=function(a){a=this.date.getTime()+1E3*MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};
MO.TDate_add=function(a){a=this.date.getTime()+MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};MO.TDate_truncDay=function(a){var b=this.date.getTime();a=b-b%(864E5*MO.Lang.Integer.nvl(a,1));this.date.setTime(a);this.refresh()};MO.TDate_truncHour=function(a){var b=this.date.getTime();a=b-b%(36E5*MO.Lang.Integer.nvl(a,1));this.date.setTime(a);this.refresh()};MO.TDate_truncMinute=function(a){var b=this.date.getTime();a=b-b%(6E4*MO.Lang.Integer.nvl(a,1));this.date.setTime(a);this.refresh()};
MO.TDate_truncSecond=function(a){var b=this.date.getTime();a=b-b%(1E3*MO.Lang.Integer.nvl(a,1));this.date.setTime(a);this.refresh()};MO.TDate_trunc=function(a){var b=this.date.getTime();a=b-b%MO.Lang.Integer.nvl(a,1);this.date.setTime(a);this.refresh()};MO.TDate_get=function(a){return this.date.getTime()};MO.TDate_set=function(a){this.date.setTime(a);this.refresh()};MO.TDate_parse=function(a,b){return MO.Lang.Date.parse(this,a,b)};
MO.TDate_parseAuto=function(a){return MO.Lang.Date.autoParse(this,a)};MO.TDate_format=function(a){return MO.Lang.Date.formatDate(this,a)};MO.TDate_clone=function(){var a=new Date;a.setTime(this.date.getTime());return new MO.TDate(a)};MO.TDate_dump=function(){return MO.Class.dump(this)+" "+MO.Lang.Date.formatDate(this)};
MO.TError=function(a,b,d){for(var e=new MO.TString,f=MO.TError.caller,g=new MO.TString,h=[];f&&!MO.Lang.Array.contains(h,f);)h.push(f),f=f.caller;for(var k=h.length,l=0;l<k;l++)f=h[l],0<l&&g.appendLine(),g.append("   "+(k-l)+": "+MO.Method.name(f));f=arguments;k=f.length;for(l=2;l<k;l++){var h=f[l],p=null,p="function"==typeof h?MO.Method.name(h):h;b=b.replace("{"+(l-1)+"}",p)}e.appendLine(b);e.appendLine("------------------------------------------------------------");e.append(g);e=e.flush();alert(e)};
MO.TListener=function(){this._callback=this._owner=null;this.process=MO.TListener_process;this.toString=MO.TListener_toString;this.dispose=MO.TListener_dispose;return this};MO.TListener_process=function(a,b,d,e,f,g){this._callback.call(this._owner?this._owner:this,a,b,d,e,f,g)};MO.TListener_toString=function(){return MO.Class.name(this)+"(owner="+MO.Class.name(this._owner)+", callback="+MO.Method.name(this._callback)+")"};MO.TListener_dispose=function(){this._callback=this._owner=null;MO.Lang.Object.free(this)};
MO.TListeners=function(){this._listeners=null;this.isEmpty=MO.TListeners_isEmpty;this.find=MO.TListeners_find;this.register=MO.TListeners_register;this.unregister=MO.TListeners_unregister;this.push=MO.TListeners_push;this.remove=MO.TListeners_remove;this.process=MO.TListeners_process;this.clear=MO.TListeners_clear;this.dispose=MO.TListeners_dispose;this.dump=MO.TListeners_dump;return this};MO.TListeners_isEmpty=function(){var a=this._listeners;return a?a.isEmpty():!0};
MO.TListeners_find=function(a,b){var d=this._listeners;if(d)for(var e=d.count(),f=0;f<e;f++){var g=d.at(f);if(g._owner==a&&g._callback==b)return g}return null};MO.TListeners_register=function(a,b){var d=this.find(a,b);if(d)throw new MO.TError(this,"Listener is already register. (owner={1}, process={2})",a,b);d=new MO.TListener;d._owner=a;d._callback=b;this.push(d);return d};
MO.TListeners_unregister=function(a,b){var d=this.find(a,b);if(!d)throw new MO.TError(this,"Listener is not register. (owner={1}, process={2})",a,b);this.remove(d);d.dispose()};MO.TListeners_push=function(a){if(!a)throw new MO.TError(this,"Listener is null.");if(!a._callback)throw new MO.TError(this,"Listener process is null.");var b=this._listeners;b||(b=this._listeners=new MO.TObjects);b.push(a)};MO.TListeners_remove=function(a){if(!a)throw new MO.TError(this,"Listener is null.");this._listeners.remove(a)};
MO.TListeners_process=function(a,b,d,e,f,g){var h=this._listeners;if(h)for(var k=h.count(),l=0;l<k;l++)h.at(l).process(a,b,d,e,f,g)};MO.TListeners_clear=function(){var a=this._listeners;a&&a.clear()};MO.TListeners_dispose=function(){var a=this._listeners;if(a){for(var b=a.count()-1;0<=b;b--)a.at(b).dispose();this._listeners=MO.Lang.Object.dispose(a)}MO.Lang.Object.free(this)};
MO.TListeners_dump=function(){var a=new MO.TString;a.append(MO.Class.name(this));for(var b=this._listeners,d=b.count(),e=0;e<d;e++)a.append("\n   "+b.at(e));return a.flush()};MO.FObject=function(a){a||(a=this);a.__class=null;a.__dispose=!1;a.__hash=0;a.construct=MO.FObject_construct;a.hashCode=MO.FObject_hashCode;a.toString=MO.FObject_toString;a.dispose=MO.FObject_dispose;a.innerDump=MO.FObject_innerDump;a.dump=MO.FObject_dump;return a};MO.FObject_construct=function(){this.__dispose=!1};
MO.FObject_hashCode=function(){var a=this.__hash;a||(a=this.__hash=MO.RObject.nextId());return a};MO.FObject_toString=function(){return MO.Class.dump(this)};MO.FObject_dispose=function(){MO.Lang.Object.free(this);this.__dispose=!0};MO.FObject_innerDump=function(a,b){a.append(MO.Class.dump(this))};MO.FObject_dump=function(){var a=new MO.TString;this.innerDump(a,0);return a.flush()};MO.RClass=function(){this._codes=[];this._classes={};return this};
MO.RClass.prototype.isBase=function(a){return null!=a?MO.Class.isBaseName(typeof a):!1};MO.RClass.prototype.isBaseName=function(a){return null==a||"boolean"!=a&&"number"!=a&&"date"!=a&&"string"!=a&&"function"!=a?!1:!0};MO.RClass.prototype.isBaseDataName=function(a){return null==a||"boolean"!=a&&"number"!=a&&"date"!=a&&"string"!=a?!1:!0};MO.RClass.prototype.isBaseType=function(a){return null==a||a!=Boolean&&a!=Number&&a!=Date&&a!=String&&a!=Function?!1:!0};
MO.RClass.prototype.isBaseDataType=function(a){return null==a||a!=Boolean&&a!=Number&&a!=Date&&a!=String?!1:!0};MO.RClass.prototype.isName=function(a,b){return this.name(a)==b};MO.RClass.prototype.isClass=function(a,b){if(a&&b){var d=this.name(b);return a.__base?null!=a.__base[d]:this.name(a)==d}return!1};MO.RClass.prototype.typeOf=function(a){return a&&a.constructor?MO.Lang.String.mid(a.constructor.toString(),"function ","("):"Null"};
MO.RClass.prototype.safeTypeOf=function(a,b){if(null==a)return"Null";try{var d=a.constructor;if(d==Boolean)return"Boolean";if(d==Number)return"Number";if(d==String)return"String";if(d==Function||d.constructor==Function)return MO.Lang.String.mid(d.toString(),"function ","(");if(a.__class)return a.__class.name;if(a.tagName)return"Html";for(var e in a)return"Object"}catch(f){}return"Unknown"};
MO.RClass.prototype.checkClass=function(a,b){if(!this.isClass(a,b))throw Error("Invalid class "+o.name(o)+"<>"+o.name(b));};MO.RClass.prototype.code=function(a){for(var b=this._codes,d=b.length,e=0;e<d;e++)if(b[e]==a)return e;b[d]=a;return d};MO.RClass.prototype.name=function(a){if(a){if(a.__name)return a.__name;if(a.__class)return a.__class.name;if("function"==typeof a)return MO.Method.name(a);if(a=a.constructor)return MO.Lang.String.mid(a.toString(),"function ","(")}return null};
MO.RClass.prototype.inherits=function(a,b){var d=MO.Runtime.nvl(b,a);d.__inherits=[];for(var e=arguments.length,f=2;f<e;f++)d.__inherits.push(MO.Method.name(arguments[f]));return d};MO.RClass.prototype.forName=function(a){var b=null;a&&(b=this._classes[a],b||(b=this.createClass(a),this.build(b)));return b};
MO.RClass.prototype.find=function(a){var b=null;null!=a&&(a.__class?b=a.__class.name:a.constructor==Function?b=MO.Method.name(a):a.constructor!=String&&MO.Logger.fatal(this,null,"Find class failure. (value={1})",a));return this._classes[b]};MO.RClass.prototype.register=function(a,b,d){a=MO.Method.name(a.constructor);a=this._classes[a];var e=null;if(b.constructor==Array)for(var f=b.length,g=0;g<f;g++)e=b[g],a.register(e);else e=b,a.register(e);b=e.value();return null!=d?d:b};
MO.RClass.prototype.createBase=function(a){var b=null;a&&(b=eval("function "+a+"(){return this;} new "+a+"();"));return b};MO.RClass.prototype.createClass=function(a){var b=this._classes[a]=new MO.TClass;b.name=a;b.base=this.createBase(a);b.clazz=new b.base.constructor;eval("MO."+a)(b.clazz);return b};MO.RClass.prototype.create=function(a){var b=null,b=typeof a;if("function"==b)b=MO.Method.name(a);else if("string"==b)b=a;else throw new MO.TError(this,"Param is invlid (clazz={1})",a);return this.createByName(b)};
MO.RClass.prototype.createByName=function(a){a=this.forName(a);if(!a)throw new MO.TError(this,"Cant find class. (name={1})",a);return a.newInstance()};
MO.RClass.prototype.innerCopy=function(a,b){if(null!=a&&null!=b)for(var d in a){var e=a[d];if(null!=e){var f=typeof e;if("function"==f){f=b[d];null==f?b[d]=e:MO.Method.isVirtual(f)?b[d]=e:!MO.Method.isVirtual(e)&&MO.Method.isEmpty(f)?b[d]=e:MO.Method.isVirtual(e)||MO.Method.isEmpty(e)||(b[d]=e);continue}else if(!MO.Class.isBaseName(f)){null==b[d]&&(b[d]=new e.constructor);this.innerCopy(e,b[d]);continue}}b[d]=e}};
MO.RClass.prototype.build=function(a){var b=a.clazz.__inherits;if(b&&b.constructor==Array)for(var d=!1,e=b.length,f=0;f<e;f++){var g=b[f];MO.Lang.String.startsWith(g,"F")&&(d&&MO.Logger.fatal(this,null,"Parent class is too many. (name={1})",g),a.parent=MO.Class.forName(g),d=!0)}d=a.instance=new a.base.constructor;if(b&&b.constructor==Array)for(e=b.length,f=0;f<e;f++)if(g=b[f],!MO.Lang.String.startsWith(g,"F")){var h=MO.Class.forName(g);null==h&&MO.Logger.fatal(this,null,"Parent class is not exists. (name={1})",
g);MO.Class.innerCopy(h.instance,d);a.assign(h)}a.parent&&(this.innerCopy(a.parent.instance,d),a.assign(a.parent));d.__base||(d.__base=new MO.TClassBase);d.__base[a.name]=new a.base.constructor;e=a.clazz;for(g in e)"__base"!=g&&(null==e[g]&&null==d[g]?d[g]=null:null!=e[g]&&(null==d[g]||null!=d[g]&&e[g]!=d[g])&&(d[g]=e[g]));if(b&&b.constructor==Array)for(e=b.length,f=0;f<e;f++){var g=b[f],k=MO.Class.forName(g),h=d.__base[g]=new k.base.constructor,k=k.instance;for(g in k)if("__base"!=g){var l=k[g],
p=d[g];null!=l&&null!=p&&l!=p&&l.constructor==Function&&p.constructor==Function&&(h[g]=k[g])}}a.build();if(MO.Runtime.isRelease())for(g in d=a.instance,d)null==d[g]&&delete a.instance[g]};MO.RClass.prototype.free=function(a){var b=a.__class;b&&b.free(a)};
MO.RClass.prototype.dump=function(a){if(null==a)return"@null";var b=this.safeTypeOf(a);switch(b){case "Boolean":return"Boolean:"+a;case "Number":return"Number:"+a;case "String":return b+"<"+a.length+">:"+a;case "Function":return b+"<"+MO.Method.name(a)+">@"+this.code(a);case "Html":return b+"<"+a.tagName+">@"+this.code(a);default:if(a.__name)return b+"<"+a.__name+">@"+this.code(a)}return b+"@"+this.code(a)};MO.RClass=new MO.RClass;MO.Class=MO.RClass;
MO.RDate=function(){this.MinYear=1800;this.MaxYear=2400;this.Pattern="n-: /";this.Chars="0123456789-:/";this.DisplayFormat="yyyy-mm-dd hh24:mi:ss";this.DataFormat="yyyymmddhh24miss";this.MonthDays=[0,31,28,31,30,31,30,31,31,30,31,30,31];this.Parts="YYYY MM DD HH24 MI SS".split(" ");this.PartsDefine={YYYY:["Year",4],MM:["Month",2],DD:["Day",2],HH24:["Hour",2],MI:["Minute",2],SS:["Second",2]};return this};MO.RDate.prototype.nvl=function(a){return a?a:new MO.TDate};
MO.RDate.prototype.format=function(a){return this.formatDate(new MO.TDate,a)};MO.RDate.prototype.formatText=function(a,b){if(!a)return!1;var d=b.toLowerCase(),d=d.replace(/yyyy/g,a.substring(0,4));a=a.substring(4);d=d.replace(/mm/g,a.substring(0,2));a=a.substring(2);d=d.replace(/dd/g,a.substring(0,2));a=a.substring(2);d=d.replace(/hh24/g,a.substring(0,4));a=a.substring(4);d=d.replace(/mi/g,a.substring(0,2));a=a.substring(2);d=d.replace(/ss/g,a.substring(0,2));a.substring(2);return d};
MO.RDate.prototype.formatDate=function(a,b){if(!a)return"";var d=b?b.toLowerCase():this.DataFormat,d=d.replace(/yyyy/g,MO.Lang.Integer.format(a.year,4)),d=d.replace(/yy/g,MO.Lang.Integer.format(a.year%100,2)),d=d.replace(/mm/g,MO.Lang.Integer.format(a.month,2)),d=d.replace(/dd/g,MO.Lang.Integer.format(a.day,2)),d=d.replace(/hh24/g,MO.Lang.Integer.format(a.hour,2)),d=d.replace(/mi/g,MO.Lang.Integer.format(a.minute,2)),d=d.replace(/ss/g,MO.Lang.Integer.format(a.second,2));return d=d.replace(/ms/g,MO.Lang.Integer.format(a.ms,
3))};MO.RDate.prototype.monthDays=function(a,b){if(!a||!b)return 0;a=parseInt(a);b=parseInt(b);this.MonthDays[2]=0!=a%4&&0!=a%400||0==a%100?28:29;return this.MonthDays[b]};
MO.RDate.prototype.splitFormat=function(a,b){if(!a)return!1;b=b.toLowerCase();for(var d=[];0<b.length;)0==b.indexOf("yyyy")?(d.year=a.substring(0,4),b=b.substring(4),a=a.substring(4)):0==b.indexOf("mm")?(d.month=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("dd")?(d.day=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("hh24")?(d.hour=a.substring(0,2),b=b.substring(4),a=a.substring(2)):0==b.indexOf("mi")?(d.minute=a.substring(0,2),b=b.substring(2),a=a.substring(2)):
0==b.indexOf("ss")?(d.second=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("ms")?(d.ms=a.substring(0,2),b=b.substring(2),a=a.substring(3)):(b=b.substring(1),a=a.substring(1));return d};
MO.RDate.prototype.splitTime=function(a,b){if(b)if(-1!=b.indexOf(":")){var d=b.split(":");1<=d.length&&(a.hour=MO.Lang.Integer.parse(d[0]));2<=d.length&&(a.minute=MO.Lang.Integer.parse(d[1]));3<=d.length&&(a.second=MO.Lang.Integer.parse(d[2]))}else 6==b.length?(a.hour=MO.Lang.Integer.parse(b.substr(0,2)),a.minute=MO.Lang.Integer.parse(b.substr(2,2)),a.second=MO.Lang.Integer.parse(b.substr(4,2))):4==b.length?(a.hour=MO.Lang.Integer.parse(b.substr(0,2)),a.minute=MO.Lang.Integer.parse(b.substr(2,2))):
2==b.length&&(a.hour=MO.Lang.Integer.parse(b.substr(0,2)))};
MO.RDate.prototype.splitDate=function(a,b){if(b)if(-1!=b.indexOf("-")||-1!=b.indexOf("/")){var d=null;-1!=b.indexOf("-")?d=b.split("-"):-1!=b.indexOf("/")&&(d=b.split("/"));1<=d.length&&(a.year=MO.Lang.Integer.parse(d[0]));2<=d.length&&(a.month=MO.Lang.Integer.parse(d[1]));3<=d.length&&(a.day=MO.Lang.Integer.parse(d[2]))}else-1!=b.indexOf(":")?this.splitTime(a,b):14==b.length?(a.year=MO.Lang.Integer.parse(b.substr(0,4)),a.month=MO.Lang.Integer.parse(b.substr(4,2)),a.day=MO.Lang.Integer.parse(b.substr(6,
2)),a.hour=MO.Lang.Integer.parse(b.substr(8,2)),a.minute=MO.Lang.Integer.parse(b.substr(10,2)),a.second=MO.Lang.Integer.parse(b.substr(12,2))):8==b.length?(a.year=MO.Lang.Integer.parse(b.substr(0,4)),a.month=MO.Lang.Integer.parse(b.substr(4,2)),a.day=MO.Lang.Integer.parse(b.substr(6,2))):6==b.length?(a.year=MO.Lang.Integer.parse(b.substr(0,4)),a.month=MO.Lang.Integer.parse(b.substr(4,2))):4==b.length&&(a.year=MO.Lang.Integer.parse(b))};
MO.RDate.prototype.checkItems=function(a){if(!a)return!1;var b=MO.Lang.Integer.parse(a.year);if(b<this.MinYear||b>this.MaxYear)return!1;var d=MO.Lang.Integer.parse(a.month);if(1>d||12<d)return!1;var e=MO.Lang.Integer.parse(a.day);if(1>e||e>this.monthDays(b,d))return!1;b=MO.Lang.Integer.parse(a.hour);if(0>b||23<b)return!1;b=MO.Lang.Integer.parse(a.second);if(0>b||59<b)return!1;a=MO.Lang.Integer.parse(a.ms);return 0>a||99<a?!1:!0};
MO.RDate.prototype.check=function(a,b){return this.checkItems(this.splitFormat(a,b))};MO.RDate.prototype.make=function(a,b,d,e,f,g){return new MO.TDate(new Date(a,b,d))};MO.RDate.prototype.makeDate=function(a,b){var d=MO.Lang.Integer.parse(b.year),e=MO.Lang.Integer.parse(b.month)-1,f=MO.Lang.Integer.parse(b.day),g=MO.Lang.Integer.parse(b.hour),h=MO.Lang.Integer.parse(b.minute),k=MO.Lang.Integer.parse(b.second),l=MO.Lang.Integer.parse(b.ms),d=new Date(d,e,f,g,h,k,l);return a?(a.setDate(d),a):new MO.TDate(d)};
MO.RDate.prototype.parse=function(a,b,d){d||(d=this.DataFormat);b=this.splitFormat(b,d);return this.checkItems(b)?this.makeDate(a,b):null};MO.RDate.prototype.autoParse=function(a,b){if(!b)return null;a=this.nvl(a);var d=[];d.year=2E3;d.month=1;d.day=1;d.hour=0;d.minute=0;d.second=0;b=MO.Lang.String.trim(b);if(-1==b.indexOf(" "))this.splitDate(d,b);else{var e=b.split(" ");2==e.length&&(this.splitDate(d,e[0]),this.splitTime(d,e[1]))}return this.checkItems(d)?this.makeDate(a,d):null};MO.RDate=new MO.RDate;
MO.Lang.Date=MO.RDate;MO.RInteger=function(){this.NUMBER=this.Chars="0123456789-%";this.LEFT_CHAR="0";this.MAX_UINT16=65535;this.MAX_UINT32=4294967295;return this};MO.RInteger.prototype.isInt=function(a){return MO.Lang.String.isPattern(a,"n")};MO.RInteger.prototype.nvl=function(a,b){return null!=a?parseInt(a):null!=b?b:0};MO.RInteger.prototype.strideByte=function(a){return 65535<a?4:255<a?2:1};MO.RInteger.prototype.strideBit=function(a){return 65535<a?32:255<a?16:8};
MO.RInteger.prototype.parse=function(a,b){null==b&&(b=0);if(null==a||""==a)return b;for(a=MO.Lang.String.trim(a.toString());"0"==a.charAt(0);)a=a.substr(1);var d=0<a.length?parseInt(a):b;return isNaN(d)?b:d};MO.RInteger.prototype.format=function(a,b,d){d||(d=this.LEFT_CHAR);a=a.toString();for(b=parseInt(b)-a.length-1;0<=b;b--)a=d+a;return a};MO.RInteger.prototype.toRange=function(a,b,d){null==a&&(a=0);isNaN(a)&&(a=0);a<b&&(a=b);a>d&&(a=d);return a};
MO.RInteger.prototype.pow2=function(a){return 4096<a?8192:2048<a?4096:1024<a?2048:512<a?1024:256<a?512:128<a?256:64<a?128:32<a?64:16<a?32:8<a?16:4<a?8:2<a?4:1<a?2:1};MO.RInteger.prototype.sum=function(){for(var a=0,b=arguments,d=b.length,e=0;e<d;e++)null!=b[e]&&(a+=parseInt(b[e]));return a};MO.RInteger.prototype.calculate=function(a,b,d){b=RInteger.parse(b);d=RInteger.parse(d);var e="";"+"==a?e=b+d:"-"==a?e=b-d:"x"==a?e=b*d:"/"==a&&(e=b/d);return e.toString()};
MO.RInteger.prototype.copy=function(a,b,d,e,f){for(var g=0;g<f;g++)a[b++]=d[e++]};MO.RInteger.prototype.toString=function(a){return null==a?"0":a.toString()};MO.RInteger=new MO.RInteger;MO.Lang.Integer=MO.RInteger;MO.RLogger=function(){this._labelLength=40;this._logger=new MO.SLogger;this.lsnsOutput=new MO.TListeners;return this};MO.RLogger.prototype.output=function(a,b){var d=this._logger;d.sender=a;d.message=b;this.lsnsOutput.process(d)};
MO.RLogger.prototype.debug=function(a,b,d){var e=null,f=MO.Logger.debug.caller;f?e=MO.Method.name(f):arguments.caller&&(e=MO.Method.name(arguments.caller[0]));e=null==e?"unknown":e.replace("_",".");a&&a.hashCode&&(e+="@"+a.hashCode());f=new MO.TString;f.append(MO.Lang.Date.format("yymmdd-hh24miss.ms"));f.append("|D ["+MO.Lang.String.rpad(e,this._labelLength)+"] ");for(var e=arguments,g=e.length,h=2;h<g;h++){var k=e[h],l="";null!=k&&(l="function"==typeof k?MO.Method.name(k):k.toString());b=b.replace("{"+
(h-1)+"}",l)}f.append(b);this.output(a,f.flush())};
MO.RLogger.prototype.info=function(a,b,d){var e=null,f=MO.Logger.info.caller;f?e=MO.Method.name(f):arguments.caller&&(e=MO.Method.name(arguments.caller[0]));e=null==e?"unknown":e.replace("_",".");a&&a.hashCode&&(e+="@"+a.hashCode());f=new MO.TString;f.append(MO.Lang.Date.format("yymmdd-hh24miss.ms"));f.append("|I ["+MO.Lang.String.rpad(e,this._labelLength)+"] ");for(var e=arguments,g=e.length,h=2;h<g;h++){var k=e[h],l="";null!=k&&(l="function"==typeof k?MO.Method.name(k):k.toString());b=b.replace("{"+
(h-1)+"}",l)}f.append(b);this.output(a,f.flush())};
MO.RLogger.prototype.warn=function(a,b,d){var e=null,f=MO.Logger.warn.caller;f?e=MO.Method.name(f):arguments.caller&&(e=MO.Method.name(arguments.caller[0]));e=null==e?"unknown":e.replace("_",".");a&&a.hashCode&&(e+="@"+a.hashCode());f=new MO.TString;f.append(MO.Lang.Date.format("yymmdd-hh24miss.ms"));f.append("|W ["+MO.Lang.String.rpad(e,this._labelLength)+"] ");for(var e=arguments,g=e.length,h=2;h<g;h++){var k=e[h],l="";null!=k&&(l="function"==typeof k?MO.Method.name(k):k.toString());b=b.replace("{"+
(h-1)+"}",l)}f.append(b);this.output(a,f.flush())};
MO.RLogger.prototype.error=function(a,b,d){var e=null,f=MO.Logger.error.caller;f?e=MO.Method.name(f):arguments.caller&&(e=MO.Method.name(arguments.caller[0]));e=null==e?"unknown":e.replace("_",".");a&&a.hashCode&&(e+="@"+a.hashCode());f=new MO.TString;f.append(MO.Lang.Date.format("yymmdd-hh24miss.ms"));f.append("|E ["+MO.Lang.String.rpad(e,this._labelLength)+"] ");for(var e=arguments,g=e.length,h=2;h<g;h++){var k=e[h],l="";null!=k&&(l="function"==typeof k?MO.Method.name(k):k.toString());b=b.replace("{"+
(h-1)+"}",l)}f.append(b);this.output(a,f.flush())};
MO.RLogger.prototype.fatal=function(a,b,d,e){for(var f=new MO.TString,g=[],h=MO.Logger.fatal.caller;h&&!MO.Lang.Array.contains(g,h);)g.push(h),h=h.caller;for(var k=g.length,l=0;l<k;l++)h=g[l],0<l&&f.appendLine(),f.append("   "+(k-l)+": "+MO.Method.name(h));g=new MO.TString;g.appendLine(MO.RContext.get("RMessage:fatal"));g.appendLine(MO.Lang.String.repeat("-",60));g.append(MO.Class.dump(a),": ");if(d)for(k=arguments.length,l=3;l<k;l++)h=arguments[l],"function"==typeof h&&(h=MO.Method.name(h)),d=d.replace("{"+
(l-2)+"}",h);g.appendLine(d);g.appendLine(MO.Lang.String.repeat("-",60));g.appendLine("Stack:");g.append(f.flush());f=g.flush();this.output(a,f);if(MO.Runtime.isPlatformPc()&&!MO.Runtime.isRelease())throw Error(f);};
MO.RLogger.prototype.show=function(a,b,d){var e=null,f=MO.Logger.show.caller;f?e=MO.Method.name(f):arguments.caller&&(e=MO.Method.name(arguments.caller[0]));e=null==e?"unknown":e.replace("_",".");owner.hashCode&&(e+="@"+owner.hashCode());f=new MO.TString;f.append(MO.Lang.Date.format("yymmdd-hh24miss.ms"));f.append("|I ["+MO.Lang.String.rpad(e,this._labelLength)+"] ");for(var e=arguments.length,g=2;g<e;g++){var h=arguments[g],k="";null!=h&&(k="function"==typeof h?MO.Method.name(h):h.toString());b=
b.replace("{"+(g-1)+"}",k)}f.append(b);alert(f.flush())};MO.Logger=new MO.RLogger;MO.RMethod=function(){this._virtuals={};this._properties={};return this};MO.RMethod.prototype.construct=function(){this.empty.__empty=!0;this.emptyTrue.__empty=!0;this.emptyFalse.__empty=!0};MO.RMethod.prototype.isFunction=function(a){return"function"==typeof a};MO.RMethod.prototype.isEmpty=function(a){return a&&a.__empty};MO.RMethod.prototype.isVirtual=function(a){return a&&a.__virtual};
MO.RMethod.prototype.name=function(a){return a&&"function"==typeof a?a.__name?a.__name:a.__name=MO.Lang.String.mid(a.toString(),"function ","("):null};MO.RMethod.prototype.fullName=function(a){return a&&a.constructor==Function?a.__fullname?a.__fullname:a.__fullname=MO.Lang.String.mid(a.toString(),"function ",")")+")":null};MO.RMethod.prototype.empty=function(){};MO.RMethod.prototype.emptyTrue=function(){return!0};MO.RMethod.prototype.emptyFalse=function(){return!1};
MO.RMethod.prototype.emptyCall=function(){};MO.RMethod.prototype.virtual=function(a,b){var d=null,e=MO.Class.name(a)+"."+b;this._virtuals[e]?d=this._virtuals[e]:(d=new Function("throw new Error('Virtual method be called.("+e+")');"),d.__virtual=!0,d.__name=e,this._virtuals[e]=d);return d};MO.RMethod.prototype.makePropertyGet=function(a,b){var d=a+"|"+b,e=null;this._properties[d]?e=this._properties[d]:(e=new Function("return this."+a+";"),this._properties[d]=e);return e};
MO.RMethod.prototype.makePropertyGetSource=function(a,b){return new Function("return this."+a+";")};MO.RMethod.prototype.makePropertySet=function(a,b){var d=a+"|"+b,e=null;this._properties[d]?e=this._properties[d]:(e=new Function("value","this."+a+"=value;"),this._properties[d]=e);return e};MO.RMethod=new MO.RMethod;MO.Method=MO.RMethod;MO.Method.construct();MO.RObject=function(){this._hash=1;return this};MO.RObject.prototype.nextId=function(a){return this._hash++};
MO.RObject.prototype.nvl=function(a){for(var b=arguments,d=b.length,e=0;e<d;e++)if(null!=b[e])return b[e];return null};MO.RObject.prototype.clone=function(a){var b=new a.constructor,d;for(d in a){var e=a[d];null!=e&&(MO.Class.isBaseType(e.constructor)||(e=MO.Lang.Object.clone(e)));b[d]=e}return b};MO.RObject.prototype.copy=function(a,b){if(null!=a&&null!=b)for(var d in a){var e=a[d];null==e||MO.Class.isBaseType(e.constructor)||(null==b[d]&&(b[d]=new c),MO.Lang.Object.copy(e,b[d]));b[d]=e}};
MO.RObject.prototype.free=function(a){if(a)if(MO.Runtime.isDebug())for(var b in a)if("__base"==b||"__inherits"==b||"__class"==b)a[b]=null;else{var d=a[b];if(null!=d){if(!MO.Class.isBaseType(d.constructor))throw new MO.TError(MO.Lang.Object,"Free object is not base object.");a[b]=null}}else for(b in a)a[b]=null};MO.RObject.prototype.dispose=function(a,b){if(a){if(a.__dispose)throw new MO.TError(MO.Lang.Object,"Object has disposed.");a.dispose(b);a.__dispose=!0}return null};
MO.RObject.prototype.release=function(a){if(a)for(var b in a){var d=a[b];"Object"==typeof d&&this.release(d);a[n]=null}return null};MO.RObject=new MO.RObject;MO.Lang.Object=MO.RObject;MO.RString=function(){this.EMPTY="";this.SPACE="   ";this.PAD=" ";this.TRIM=" \t\r\n";this.LOWER="abcdefghijklmnopqrstuvwxyz";this.UPPER="ABCDEFGHIJKLMNOPQRSTUVWXYZ";this.CodeLowerA=97;this.CodeLowerZ=122;this.CodeUpperA=65;this.CodeUpperZ=90;this._hashData=null;return this};
MO.RString.prototype.isEmpty=function(a){return null!=a?0==a.length:!0};MO.RString.prototype.isBlank=function(a){return null!=a?0==a.trim().length:!0};MO.RString.prototype.isAnsi=function(a){if(null!=a){for(var b=a.length,d=0;d<b;d++)if(255<a.charCodeAt(d))return!1;return!0}return!1};MO.RString.prototype.isDbcs=function(a){if(null==a){for(var b=a.length,d=0;d<b;d++)if(256>a.charCodeAt(d))return!1;return!0}return!1};
MO.RString.prototype.isPattern=function(a,b){if(null!=a){var d;d=(null==b?"$a$A$f":b).replace(/\a/g,this.LOWER);d=d.replace(/\A/g,this.UPPER);d=d.replace(/\f/g,MO.Lang.Float.NUMBER);d=d.replace(/\n/g,MO.Lang.Integer.NUMBER);for(var e=a.length,f=0;f<e;f++)if(-1==d.indexOf(a.charAt(f)))return!1;return!0}return!1};MO.RString.prototype.inChars=function(a,b){return-1!=this.findChars(b,a)?!0:!1};
MO.RString.prototype.equals=function(a,b,d){null==a?a="":a.constructor!=String&&(a=a.toString());null==b?b="":b.constructor!=String&&(b=b.toString());return d?a==b:a.toLowerCase()==b.toLowerCase()};MO.RString.prototype.contains=function(a,b){if(null!=a){a.constructor!=String&&(a=a.toString());for(var d=arguments.length,e=1;e<d;e++)if(-1!=a.indexOf(arguments[e]))return!0}return!1};MO.RString.prototype.startsWith=function(a,b){return null==b?!0:null!=a?0==a.indexOf(b):!1};
MO.RString.prototype.endsWith=function(a,b){if(null==b)return!0;var d=null!=a?a.indexOf(b):-1;return-1!=d?d==a.length-b.length:!1};MO.RString.prototype.findChars=function(a,b){if(null!=a&&null!=b)for(var d=a.length,e=0;e<d;e++)if(-1!=b.indexOf(a.charAt(e)))return e;return-1};MO.RString.prototype.inRange=function(a,b,d){if(a&&b){d||(a=a.toLowerCase());for(var e=b.length,f=0;f<e;f++){var g=b[f];if(null!=g)if(d){if(a==g)return!0}else if(a==g.toLowerCase())return!0}}return!1};
MO.RString.prototype.nvl=function(a,b){if(null!=a){var d=null,d=a.constructor!=String?a.toString():a;if(0<d.length)return d}return null!=b?b:this.EMPTY};MO.RString.prototype.nvlString=function(a){null==a&&(a=new MO.TString);return a};MO.RString.prototype.empty=function(a){if(null!=a){var b=null,b=a.constructor!=String?a.toString():a;if(0<b.length)return b}return null};
MO.RString.prototype.calculateHash=function(a,b){var d=this._hashData;d||(d=this._hashData=new Int32Array(1));d[0]=MO.Runtime.nvl(b,0);for(var e=a.length,f=0;f<e;f++){var g=a.charCodeAt(f);d[0]=31*d[0]+g}return Math.abs(d[0])};MO.RString.prototype.firstUpper=function(a){return null!=a?a.charAt(0).toUpperCase()+a.substr(1):a};MO.RString.prototype.firstLower=function(){return null!=value?value.charAt(0).toLowerCase()+value.substr(1):value};
MO.RString.prototype.firstLine=function(a){if(a){var b=Math.min(a.indexOf("\r"),a.indexOf("\n"));return-1!=b?a.substr(0,b):a}return""};MO.RString.prototype.format=function(a,b){for(var d=arguments.length,e=1;e<d;e++){var f=arguments[e];null==f?f="":"function"==typeof f&&(f=MO.Method.name(f));a=a.replace("{"+e+"}",f)}return a};
MO.RString.prototype.formatLines=function(a){a=a.replace(/\\r/g,"");a=a.split("\n");for(var b=a.length,d=new MO.TString,e=0;e<b;e++){var f=a[e],f=this.trim(f);this.isEmpty(f)||this.startsWith(f,"//")||d.appendLine(f)}return d.flush()};MO.RString.prototype.repeat=function(a,b){return Array(b+1).join(a)};MO.RString.prototype.pad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;if(0<b){null==d&&(d=this.PAD);var e=0==b%2?b/2:(b-1)/2;return Array(e+1).join(d)+a+Array(b-e+1).join(d)}return a};
MO.RString.prototype.lpad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;return 0<b?(null==d&&(d=this.PAD),b=Array(b),b[b.length]=a,b.join(d)):a};MO.RString.prototype.rpad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;return 0<b?(null==d&&(d=this.PAD),a+Array(b+1).join(d)):a};
MO.RString.prototype.trim=function(a,b){a=this.nvl(a);b=this.nvl(b,this.TRIM);for(var d=0,e=a.length-1;d<e&&-1!=b.indexOf(a.charAt(d));d++);for(;e>=d&&-1!=b.indexOf(a.charAt(e));e--);return d==e+1?null:0!=d||e!=a.length-1?a.substring(d,e+1):a};MO.RString.prototype.ltrim=function(a,b){a=this.nvl(value);b=this.nvl(trims,this.TRIM);for(var d=0,e=a.length-1;d<e&&-1!=b.indexOf(a.charAt(d));d++);return 0!=d?a.substring(d,e+1):a};
MO.RString.prototype.rtrim=function(a,b){a=this.nvl(a);b=this.nvl(b,this.TRIM);for(var d=a.length-1;0<=d&&-1!=b.indexOf(a.charAt(d));d--);return d!=a.length-1?a.substring(0,d+1):a};MO.RString.prototype.mid=function(a,b,d){if(null==a)return a;var e=0;if(null!=b){var f=a.indexOf(b);-1!=f&&(e=f+b.length)}b=a.length;null!=d&&(f=a.indexOf(d,e),-1!=f&&(b=f));return a.substring(e,b)};MO.RString.prototype.toLine=function(a){return a.replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")};
MO.RString.prototype.toUnderline=function(a){var b=null;if(a){for(var b=new MO.TString,d=a.length,e=0;e<d;e++){var f=a.charAt(e);f.toUpperCase()==f?(0<e&&b.append("_"),b.append(f.toLowerCase())):b.append(f)}b=b.flush()}return b};MO.RString.prototype.toLower=function(a){return null!=a?a.toLowerCase():this.EMPTY};MO.RString.prototype.toUpper=function(a){return null!=a?a.toUpperCase():this.EMPTY};MO.RString.prototype.split=function(a,b){return a&&b?a.split(b):null};
MO.RString.prototype.splitTwo=function(a,b){if(a&&b){var d=[],e=a.indexOf(b);-1==e?d.push(a):(d.push(a.substring(0,e)),d.push(a.substring(e+b.length)));return d}return null};MO.RString.prototype.splitParts=function(a,b){for(var d=[],e=0,f=a.length,g=0;g<f;g++)for(var h in b)if(this.startsWith(b[h],a.charAt(g))&&this.equals(a.substr(g,b[h].length),b[h])){d[e++]=b[h];g=g+b[h].length-1;break}return d};
MO.RString.prototype.splitPattern=function(a,b){var d=[];if(a)for(var e=a.length,f=b.length,g="",h=0;h<e;h++){for(var k=!1,l=0;l<f;l++){var p=b[l];if(-1==a.indexOf(p)){g.length&&(d[d.length]=g,g="");d[d.length]=p;a=a.substring(p.length);k=!0;break}}k||(g+=a.charAt(0),a=a.substring(1))}return d};MO.RString.prototype.replace=function(a,b,d){return a.replace(new RegExp(b,"g"),d)};
MO.RString.prototype.replaceChar=function(a,b,d){if(null!=a){for(var e=a.length,f=[],g=0;g<e;g++){var h=a.charAt(g);f[f.length]=h==b?d:h}return f.join("")}return a};
MO.RString.prototype.decodeUtf=function(a){for(var b=0,d=0,e=0,f=0,g=0,h=a.length,k=[],l=[];b<h;++b,++d){e=a[b]&255;if(e&128)if(192==(e&224)){if(b+1>=h)return a;f=a[++b]&255;if(128!=(f&192))return a;l[d]=(e&31)<<6|f&63}else if(224==(e&240)){if(b+2>=h)return a;f=a[++b]&255;if(128!=(f&192))return a;g=a[++b]&255;if(128!=(g&192))return a;l[d]=(e&15)<<12|(f&63)<<6|g&63}else return a;else{if(!e)return a;l[d]=e}if(65535==d){d=l.length;for(e=0;e<d;e++)k.push(String.fromCharCode(l[e]));d=-1}}if(0<d)for(l.length=
d,d=l.length,e=0;e<d;e++)k.push(String.fromCharCode(l[e]));return k.join("")};MO.RString.prototype.remove=function(a,b){return a.replace(b,"")};MO.RString.prototype.removeChars=function(a,b){if(null!=a){for(var d=a.length,e=[],f=0;f<d;f++){var g=a.charAt(f);-1==b.indexOf(g)&&(e[e.length]=g)}return e.join("")}return a};MO.RString=new MO.RString;MO.Lang.String=MO.RString;MO.AListener=function(a,b){MO.ASource.call(this,a,MO.ESource.Listener,b);this.build=MO.AListener_build;return this};
MO.AListener_build=function(a,b){var d="add"+this._linker+"Listener";b[d]=MO.RListener.makeAddListener(d,this._linker);d="set"+this._linker+"Listener";b[d]=MO.RListener.makeSetListener(d,this._linker);d="remove"+this._linker+"Listener";b[d]=MO.RListener.makeRemoveListener(d,this._linker);d="clear"+this._linker+"Listeners";b[d]=MO.RListener.makeClearListener(d,this._linker);d="process"+this._linker+"Listener";b[d]=MO.RListener.makeProcessListener(d,this._linker)};
MO.EEvent=new function(){this.Unknown="Unknown";this.Load="Load";this.Loaded="Loaded";this.Process="Process";this.Complete="Complete";this.Change="Change";this.EnterFrame="EnterFrame";this.LeaveFrame="LeaveFrame";this.Enter="Enter";this.Leave="Leave";this.Resize="Reisze";this.Focus="Focus";this.Blur="Blur";this.MouseDown="MouseDown";this.MouseMove="MouseMove";this.MouseUp="MouseUp";this.MouseWheel="MouseWheel";this.KeyDown="KeyDown";this.KeyPress="KeyPress";this.KeyUp="KeyUp";this.Click="Click";this.DoubleClick=
"DoubleClick";this.NodeClick="NodeClick";this.ItemClick="ItemClick";this.Selected="Selected";this.DataChanged="DataChanged";this.Result="Result";this.TouchZoom="TouchZoom";this.Visibility="Visibility";this.Orientation="Orientation";this.OperationDown="OperationDown";this.OperationMove="OperationMove";this.OperationUp="OperationUp";return this};MO.EHttpContent=new function(){this.Binary=1;this.Text=2;return this};MO.EHttpMethod=new function(){this.Get="GET";this.Post="POST";return this};
MO.EHttpStatus=new function(){this.Uninitialized=0;this.Open=1;this.Send=2;this.Receiving=3;this.Loaded=4;return this};MO.EOrientation=new function(){this.Unknown=0;this.Horizontal="H";this.Vertical="V";return this};
MO.MListener=function(a){a=MO.Class.inherits(this,a);a._listenerss=null;a.addListener=MO.MListener_addListener;a.setListener=MO.MListener_setListener;a.removeListener=MO.MListener_removeListener;a.clearListeners=MO.MListener_clearListeners;a.clearAllListeners=MO.MListener_clearAllListeners;a.processListener=MO.MListener_processListener;a.dispose=MO.MListener_dispose;return a};
MO.MListener_addListener=function(a,b,d){var e=this._listenerss;e||(e=this._listenerss=new MO.TDictionary);var f=e.get(a);f||(f=new MO.TListeners,e.set(a,f));return f.register(b,d)};MO.MListener_setListener=function(a,b,d){var e=this._listenerss;e&&(e=e.get(a))&&e.clear();return this.addListener(a,b,d)};MO.MListener_removeListener=function(a,b,d){return this._listenerss.get(a).unregister(b,d)};MO.MListener_clearListeners=function(a){var b=this._listenerss;b&&(a=b.get(a))&&a.clear()};
MO.MListener_clearAllListeners=function(){var a=this._listenerss;if(a)for(var b=a.count(),d=0;d<b;d++){var e=a.at(d);e&&e.clear()}};MO.MListener_processListener=function(a,b,d,e,f,g){var h=this._listenerss;h&&(a=h.get(a))&&a.process(b,d,e,f,g)};MO.MListener_dispose=function(){var a=this._listenerss;if(a){for(var b=a.count()-1;0<=b;b--)a.at(b).dispose();this._listenerss=MO.Lang.Object.dispose(a)}};
MO.SEvent=function(a){this.listener=this.annotation=this.code=null;this.sender=a;this.process=this.onProcess=this.ohProcess=this.hSource=this.hSender=this.hEvent=this.source=null;this.dispose=MO.SEvent_dispose;return this};MO.SEvent_dispose=function(){for(var a in this)this[a]=null};MO.SKeyboardEvent=function(){MO.SEvent.call(this);this.ctrlKey=this.shiftKey=this.altKey=!1;this.keyCode=0;this.attachEvent=MO.SKeyboardEvent_attachEvent;this.cancel=MO.SKeyboardEvent_cancel;return this};
MO.SKeyboardEvent_attachEvent=function(a){this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.ctrlKey=a.ctrlKey;this.keyCode=a.keyCode};MO.SKeyboardEvent_cancel=function(){this.hEvent.returnValue=!1};MO.SMouseEvent=function(){MO.SEvent.call(this);this.button=null;this.ctrlKey=this.altKey=this.mouseRight=this.mouseMiddle=this.mouseLeft=!1;this.deltaZ=this.deltaY=this.deltaX=this.clientY=this.clientX=this.offsetY=this.offsetX=this.y=this.x=0;this.attachEvent=MO.SMouseEvent_attachEvent;return this};
MO.SMouseEvent_attachEvent=function(a){var b=this.hSource=MO.RHtml.eventSource(a);b&&(this.source=b.__linker);this.button=a.button;this.mouseLeft=a.button==MO.EMouseButton.Left;this.mouseMiddle=a.button==MO.EMouseButton.Middle;this.mouseRight=a.button==MO.EMouseButton.Right;this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;MO.RBrowser.isBrowser(MO.EBrowser.FireFox)?(this.x=a.pageX,this.y=a.pageY,this.offsetX=a.layerX,this.offsetY=a.layerY):(this.x=a.x,this.y=a.y,this.offsetX=a.offsetX,this.offsetY=a.offsetY);
this.clientX=a.clientX;this.clientY=a.clientY;this.deltaX=a.deltaX;this.deltaY=a.deltaY;this.deltaZ=a.deltaZ};MO.SResizeEvent=function(){MO.SEvent.call(this);this.height=this.width=null;this.attachEvent=MO.SResizeEvent_attachEvent;return this};MO.SResizeEvent_attachEvent=function(a){if(a=this.hSource=MO.RHtml.eventSource(a))this.source=a.__linker};
MO.FHttpConnection=function(a){a=MO.Class.inherits(this,a,MO.FObject,MO.MListener);a._asynchronous=MO.Class.register(a,new MO.AGetSet("_asynchronous"),!1);a._methodCd=MO.EHttpMethod.Get;a._contentCd=MO.EHttpContent.Binary;a._url=null;a._heads=MO.Class.register(a,new MO.AGetter("_heads"));a._attributes=MO.Class.register(a,new MO.AGetter("_attributes"));a._input=null;a._inputData=MO.Class.register(a,new MO.AGetSet("_inputData"));a._output=null;a._outputData=MO.Class.register(a,new MO.AGetter("_outputData"));
a._handle=null;a._contentLength=0;a._statusFree=!0;a._event=null;a._listenersLoad=MO.Class.register(a,new MO.AListener("_listenersLoad",MO.EEvent.Load));a._listenersComplete=MO.Class.register(a,new MO.AListener("_listenersComplete",MO.EEvent.Complete));a.onConnectionSend=MO.FHttpConnection_onConnectionSend;a.onConnectionReady=MO.FHttpConnection_onConnectionReady;a.onConnectionComplete=MO.FHttpConnection_onConnectionComplete;a.construct=MO.FHttpConnection_construct;a.header=MO.FHttpConnection_header;
a.setHeader=MO.FHttpConnection_setHeader;a.setHeaders=MO.FHttpConnection_setHeaders;a.setOutputData=MO.FHttpConnection_setOutputData;a.content=MO.FHttpConnection_content;a.reset=MO.FHttpConnection_reset;a.sendSync=MO.FHttpConnection_sendSync;a.sendAsync=MO.FHttpConnection_sendAsync;a.send=MO.FHttpConnection_send;a.post=MO.FHttpConnection_post;a.dispose=MO.FHttpConnection_dispose;return a};
MO.FHttpConnection_onConnectionSend=function(){var a=this._input;if(a)if(a.constructor==String)this._inputData=a,this._contentLength=a.length;else if(a.constructor==ArrayBuffer)this._inputData=a,this._contentLength=a.byteLength;else throw new MO.TError("Unknown send data type.");};
MO.FHttpConnection_onConnectionReady=function(){var a=this._linker;if(a._asynchronous){var b=a._handle;b.readyState==MO.EHttpStatus.Loaded&&(200==b.status?(a.setOutputData(),a.onConnectionComplete()):MO.Logger.fatal(a,"Connection failure. (url={1})",a._url))}};
MO.FHttpConnection_onConnectionComplete=function(){this._statusFree=!0;var a=this._event;a.connection=this;a.content=this._outputData;for(var b=this._attributes,d=b.count(),e=0;e<d;e++){var f=b.name(e),g=b.value(e);a[f]=g}this.processLoadListener(a);this.processCompleteListener(a)};
MO.FHttpConnection_construct=function(){this.__base.FObject.construct.call(this);this._heads=new MO.TAttributes;this._attributes=new MO.TAttributes;this._event=new MO.SEvent;var a=this._handle=MO.Window.Xml.createConnection();a._linker=this;a.onreadystatechange=this.onConnectionReady};MO.FHttpConnection_header=function(a){return this._heads.get(a)};MO.FHttpConnection_setHeader=function(a,b){this._heads.set(a,b)};
MO.FHttpConnection_setHeaders=function(){var a=this._handle;this._contentCd==MO.EHttpContent.Binary?MO.Window.Browser.isBrowser(MO.EBrowser.Explorer)?(a.setRequestHeader("Accept-Charset","x-user-defined"),a.responseType="arraybuffer"):(a.overrideMimeType("text/plain; charset=x-user-defined"),this._asynchronous&&(a.responseType="arraybuffer")):a.setRequestHeader("content-type","application/x-www-form-urlencoded");var b=this._heads,d=b.count();if(0<d)for(var e=0;e<d;e++){var f=b.name(e),g=b.value(e);
a.setRequestHeader(f,g)}MO.Window.Browser.isBrowser(MO.EBrowser.Chrome)||(b=this._contentLength,0<b&&a.setRequestHeader("content-length",b))};MO.FHttpConnection_setOutputData=function(){var a=this._handle;this._outputData=this._contentCd==MO.EHttpContent.Binary?a.response:a.responseText};MO.FHttpConnection_content=function(){return this._outputData};MO.FHttpConnection_reset=function(){this._handle.abort();this._attributes.clear();this.clearAllListeners()};
MO.FHttpConnection_sendSync=function(){var a=this._handle;a.open(this._methodCd,this._url,!1);this.setHeaders(a,0);a.send(this._inputData);this.setOutputData();this.onConnectionComplete();MO.Logger.info(this,"Send http sync request. (method={1}, url={2})",this._methodCd,this._url)};
MO.FHttpConnection_sendAsync=function(){var a=this._handle;a.open(this._methodCd,this._url,!0);this.setHeaders(a,0);a.send(this._inputData);MO.Logger.info(this,"Send http asynchronous request. (method={1}, url={2})",this._methodCd,this._url)};MO.FHttpConnection_send=function(a,b){this._url=a;this._input=b;this._methodCd=null!=b?MO.EHttpMethod.Post:MO.EHttpMethod.Get;this._statusFree=!1;this.onConnectionSend();this._asynchronous?this.sendAsync():this.sendSync();return this.content()};
MO.FHttpConnection_post=function(a,b){this._url=a;this._input=b;this._methodCd=MO.EHttpMethod.Post;this._statusFree=!1;this.onConnectionSend();this._asynchronous?this.sendAsync():this.sendSync();return this.content()};
MO.FHttpConnection_dispose=function(){this._heads=MO.Lang.Object.dispose(this._heads);this._attributes=MO.Lang.Object.dispose(this._attributes);this._event=MO.Lang.Object.dispose(this._event);this._outputData=this._output=this._inputData=this._input=null;var a=this._handle;a&&(this._handle=a.onreadystatechange=null);this.__base.MListener.dispose.call(this);this.__base.FObject.dispose.call(this)};MO.RListener=function(){this._listeners={};return this};
MO.RListener.prototype.makeAddListener=function(a,b){var d=null;this._listeners[a]?d=this._listeners[a]:(d=new Function("owner","callback","return this.addListener('"+b+"',owner,callback);"),this._listeners[a]=d);return d};MO.RListener.prototype.makeSetListener=function(a,b){var d=null;this._listeners[a]?d=this._listeners[a]:(d=new Function("owner","callback","return this.setListener('"+b+"',owner,callback);"),this._listeners[a]=d);return d};
MO.RListener.prototype.makeRemoveListener=function(a,b){var d=null;this._listeners[a]?d=this._listeners[a]:(d=new Function("owner","callback","return this.removeListener('"+b+"',owner,callback);"),this._listeners[a]=d);return d};MO.RListener.prototype.makeClearListener=function(a,b){var d=null;this._listeners[a]?d=this._listeners[a]:(d=new Function("return this.clearListeners('"+b+"');"),this._listeners[a]=d);return d};
MO.RListener.prototype.makeProcessListener=function(a,b){var d=null;this._listeners[a]?d=this._listeners[a]:(d=new Function("p1","p2","p3","p4","p5","p6","return this.processListener('"+b+"', p1, p2, p3, p4, p5, p6);"),this._listeners[a]=d);return d};MO.RListener=new MO.RListener;MO.EBrowser=new function(){this.Unknown="unknown";this.Explorer="explorer";this.FireFox="firefox";this.Chrome="chrome";this.Safari="safari";return this};
MO.EDevice=new function(){this.Unknown="unknown";this.Pc="pc";this.Mobile="mobile";return this};MO.ESoftware=new function(){this.Unknown="unknown";this.Window="window";this.Linux="linux";this.Android="android";this.Apple="apple";return this};
MO.RWindow=function(){this._optionSelect=!0;this._statusError=!1;this._statusEnable=!0;this._disableDeep=0;this._cookies=new MO.TAttributes;this._sessionStorage=this._localStorage=null;this._eventMouse=new MO.SMouseEvent;this._eventKey=new MO.SKeyboardEvent;this._eventResize=new MO.SResizeEvent;this._eventVisibility=new MO.SEvent;this._eventOrientation=new MO.SEvent;this._eventUnload=new MO.SEvent;this._hDisableImage=this._hDisablePanel=this._hContainer=this._hDocument=this._hWindow=null;this.lsnsLoad=
new MO.TListeners;this.lsnsLoaded=new MO.TListeners;this.lsnsUnload=new MO.TListeners;this.lsnsMouseDown=new MO.TListeners;this.lsnsMouseUp=new MO.TListeners;this.lsnsMouseOver=new MO.TListeners;this.lsnsMouseMove=new MO.TListeners;this.lsnsMouseWheel=new MO.TListeners;this.lsnsKeyDown=new MO.TListeners;this.lsnsKeyUp=new MO.TListeners;this.lsnsKeyPress=new MO.TListeners;this.lsnsResize=new MO.TListeners;this.lsnsVisibility=new MO.TListeners;this.lsnsOrientation=new MO.TListeners;this.lsnsDeviceError=
new MO.TListeners;return this};MO.RWindow.prototype.ohMouseDown=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventMouse;d.code=MO.EEvent.MouseDown;d.attachEvent(a);b.lsnsMouseDown.process(d)};MO.RWindow.prototype.ohMouseMove=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventMouse;d.code=MO.EEvent.MouseMove;d.attachEvent(a);b.lsnsMouseMove.process(d)};
MO.RWindow.prototype.ohMouseUp=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventMouse;d.code=MO.EEvent.MouseUp;d.attachEvent(a);b.lsnsMouseUp.process(d)};MO.RWindow.prototype.ohMouseWheel=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventMouse;d.code=MO.EEvent.MouseWheel;d.attachEvent(a);b.lsnsMouseWheel.process(d)};MO.RWindow.prototype.ohKeyDown=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventKey;d.code=MO.EEvent.KeyDown;d.attachEvent(a);b.lsnsKeyDown.process(d)};
MO.RWindow.prototype.ohKeyUp=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventKey;d.code=MO.EEvent.KeyUp;d.attachEvent(a);b.lsnsKeyUp.process(d)};MO.RWindow.prototype.ohKeyPress=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventKey;d.code=MO.EEvent.KeyPress;d.attachEvent(a);b.lsnsKeyPress.process(d)};MO.RWindow.prototype.ohResize=function(a){var b=MO.Window;a||(a=b._hWindow.event);var d=b._eventResize;d.code=MO.EEvent.Resize;d.attachEvent(a);b.lsnsResize.process(d)};
MO.RWindow.prototype.ohSelect=function(a){return MO.Window._optionSelect};MO.RWindow.prototype.ohVisibility=function(a){a=MO.Window;var b=MO.Window.Browser.isVisibility(),d=a._eventVisibility;d.visibility=b;a.lsnsVisibility.process(d)};MO.RWindow.prototype.ohOrientation=function(a){a=MO.Window;var b=a.Browser.refreshOrientation(),d=a._eventOrientation;d.orientationCd=b;a.lsnsOrientation.process(d)};
MO.RWindow.prototype.ohUnload=function(a){var b=MO.Window;a=b._eventUnload;b.lsnsUnload.process(a);b.dispose()};
MO.RWindow.prototype.connect=function(a){this._eventVisibility.code=MO.EEvent.Visibility;this._eventOrientation.code=MO.EEvent.Orientation;a=this._hWindow=a;var b=this._hDocument=a.document,d=this._hContainer=b.body,e=MO.Window.Browser.defineEventGet("visibilitychange");MO.Window.Browser.supportHtml5()?(d.addEventListener("mousedown",this.ohMouseDown,!0),d.addEventListener("mousemove",this.ohMouseMove,!0),d.addEventListener("mouseup",this.ohMouseUp,!0),d.addEventListener("mousewheel",this.ohMouseWheel,
!0),d.addEventListener("keydown",this.ohKeyDown,!0),d.addEventListener("keyup",this.ohKeyUp,!0),d.addEventListener("keypress",this.ohKeyPress,!0),b.addEventListener(e,this.ohVisibility,!0)):(d.onmousedown=this.ohMouseDown,d.onmousemove=this.ohMouseMove,d.onmouseup=this.ohMouseUp,d.onmousewheel=this.ohMouseWheel,d.onkeydown=this.ohKeyDown,d.onkeyup=this.ohKeyUp,d.onkeypress=this.ohKeyPress,b["on"+e]=this.ohVisibility);a.onorientationchange=this.ohOrientation;d.onresize=this.ohResize;d.onselectstart=
this.ohSelect;d.onunload=this.ohUnload;this._cookies.split(b.cookie,"=",";");this._requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame;this._cancelAnimationFrame=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.msCancelAnimationFrame||
window.msCancelRequestAnimationFrame};MO.RWindow.prototype.htmlWindow=function(){return this._hWindow};MO.RWindow.prototype.optionSelect=function(){return this._optionSelect};MO.RWindow.prototype.setOptionSelect=function(a){this._optionSelect=a;MO.Window.Browser.isBrowser(MO.EBrowser.FireFox)&&(this._hContainer.style.MozUserSelect=a?"":"none")};MO.RWindow.prototype.statusError=function(){return this._statusError};MO.RWindow.prototype.setStatusError=function(a){this._statusError=a};
MO.RWindow.prototype.processDeviceError=function(a){this._statusError=!0;this.lsnsDeviceError.process(a)};MO.RWindow.prototype.setCaption=function(a){top.document.title=MO.Lang.String.nvl(a)};MO.RWindow.prototype.setStatus=function(a){window.status=MO.Lang.String.nvl(a)};MO.RWindow.prototype.cookies=function(){return this._cookies};MO.RWindow.prototype.cookie=function(a){return this._cookies.get(a)};
MO.RWindow.prototype.storage=function(a){switch(a){case MO.EScope.Local:return a=this._localStorage,a||(a=this._localStorage=MO.Class.create(MO.FWindowStorage),a.link(window.localStorage)),a;case MO.EScope.Session:return a=this._sessionStorage,a||(a=this._sessionStorage=MO.Class.create(MO.FWindowStorage),a.link(window.sessionStorage)),a}throw new TError(this,"Unknown scope. (scope_cd={1})",a);};
MO.RWindow.prototype.makeDisablePanel=function(a){var b=this._hDisablePanel;b||(b=this._hDisablePanel=MO.Window.Builder.createDiv(this._hDocument,"RWindow_Disable"),b.style.zIndex=5E3);var d=this._hDisableImage;d||(d=this._hDisableImage=MO.Window.Builder.appendIcon(b),d.src=MO.RResource.iconPath("control.RWindow_Loading"),d.style.margin=this._hContainer.offsetHeight/2,d.style.display="none");MO.Window.Html.visibleSet(d,a);return b};
MO.RWindow.prototype.windowDisable=function(){this._hContainer.disabled=!0};MO.RWindow.prototype.windowEnable=function(){this._hContainer.disabled=!1};MO.RWindow.prototype.isEnable=function(){return this._statusEnable};MO.RWindow.prototype.enable=function(){this._disableDeep--;0==this._disableDeep&&this.setEnable(!0)};MO.RWindow.prototype.disable=function(){0==this._disableDeep&&this.setEnable(!1);this._disableDeep++};
MO.RWindow.prototype.setEnable=function(a,b){var d=this.makeDisablePanel(b);if(a)this.windowEnable(),d._linked&&(this._hContainer.removeChild(d),d._linked=!1);else{var e=this._hDocument,f=this._hDisablePanel.style;f.left="0px";f.top="0px";f.width=(e.all?this._hContainer.scrollWidth:e.documentElement.scrollWidth)+"px";f.height=(e.all?this._hContainer.scrollHeight:e.documentElement.scrollHeight)+"px";d._linked||(this._hContainer.appendChild(d),d._linked=!0)}this._statusEnable=a};
MO.RWindow.prototype.appendElement=function(a){this._hContainer.appendChild(a)};MO.RWindow.prototype.requestAnimationFrame=function(a){var b=this._requestAnimationFrame;return b?(b(a),!0):!1};MO.RWindow.prototype.cancelRequestAnimationFrame=function(a){var b=this._cancelAnimationFrame;return b?(b(a),!0):!1};MO.RWindow.prototype.redirect=function(){};MO.RWindow.prototype.historyForward=function(){};MO.RWindow.prototype.historyBack=function(){};
MO.RWindow.prototype.dispose=function(){var a=this._hWindow,b=this._hContainer;MO.Window.Browser.supportHtml5()?(b.removeEventListener("mousedown",this.onMouseDown,!0),b.removeEventListener("mousemove",this.onMouseMove,!0),b.removeEventListener("mouseup",this.onMouseUp,!0),b.removeEventListener("mousewheel",this.onMouseWheel,!0),b.removeEventListener("keydown",this.onKeyDown,!0),b.removeEventListener("keyup",this.onKeyUp,!0),b.removeEventListener("keypress",this.onKeyPress,!0),a.removeEventListener("orientationchange",
this.onOrientation)):(b.onmousedown=null,b.onmousemove=null,b.onmouseup=null,b.onmousewheel=null,b.onkeydown=null,b.onkeyup=null,b.onkeypress=null,a.onorientationchange=null);b.onresize=null;b.onselectstart=null;b.onunload=null;this._localStorage=MO.Lang.Object.dispose(this._localStorage);this._sessionStorage=MO.Lang.Object.dispose(this._sessionStorage);this._hContainer=this._hDocument=this._hWindow=null;this._eventMouse=MO.Lang.Object.dispose(this._eventMouse);this._eventKey=MO.Lang.Object.dispose(this._eventKey);
this._eventResize=MO.Lang.Object.dispose(this._eventResize);this._eventOrientation=MO.Lang.Object.dispose(this._eventOrientation);this._eventUnload=MO.Lang.Object.dispose(this._eventUnload)};MO.RWindow=new MO.RWindow;MO.Window=MO.RWindow;MO.SBrowserCapability=function(){this.optionStorage=this.optionProcess=!1;this.canvasScale=!0;this.soundConfirm=!1;this.soundFinish=!0;this.blobCreate=!1;this.pixelRatio=1;return this};
MO.FWindowStorage=function(a){a=MO.Class.inherits(this,a,MO.FObject);a._scopeCd=MO.Class.register(a,new MO.AGetter("_scopeCd"));a._storage=null;a.link=MO.FWindowStorage_link;a.get=MO.FWindowStorage_get;a.set=MO.FWindowStorage_set;a.remove=MO.FWindowStorage_remove;a.clear=MO.FWindowStorage_clear;a.dispose=MO.FWindowStorage_dispose;a.innerDump=MO.FWindowStorage_innerDump;return a};MO.FWindowStorage_link=function(a){this._storage=a};MO.FWindowStorage_get=function(a){return this._storage.getItem(a)};
MO.FWindowStorage_set=function(a,b){this._storage.setItem(a,b)};MO.FWindowStorage_remove=function(a){this._storage.removeItem(a)};MO.FWindowStorage_clear=function(){this._storage.clear()};MO.FWindowStorage_dispose=function(){this._storage=null;this.__base.FObject.dispose.call(this)};MO.FWindowStorage_innerDump=function(a,b){for(var d=this._storage,e=d.length,f=0;f<e;f++){var g=d.key(f),h=d.getItem(g);0<f&&a.append(";");a.append(g+"="+h)}};
MO.RBrowser=function(){this._defineMethods=this._defineEvents=this._defineProperties=this._capability=this._agent=null;this._deviceCd=MO.EDevice.Unknown;this._softwareCd=MO.ESoftware.Unknown;this._typeCd=MO.EBrowser.Unknown;this._orientationCd=MO.EOrientation.Horizontal;this._supportHtml5=!1;this._contentPath=this._hostPath="";return this};MO.RBrowser.prototype.onLog=function(a){console.log(a.message)};
MO.RBrowser.prototype.construct=function(){var a=(this._agent=window.navigator.userAgent.toString()).toLowerCase(),b=this._defineProperties={},d=this._defineEvents={};this._defineMethods={};var e=this._capability=new MO.SBrowserCapability;-1!=a.indexOf("android")&&(this._typeCd=MO.EDevice.Mobile,this._softwareCd=MO.ESoftware.Android);if(-1!=a.indexOf("chrome"))this._typeCd=MO.EBrowser.Chrome;else if(-1!=a.indexOf("firefox"))this._typeCd=MO.EBrowser.FireFox;else if(-1!=a.indexOf("msie")||-1!=a.indexOf("windows"))this._typeCd=
MO.EBrowser.Explorer;else if(-1!=a.indexOf("safari")||-1!=a.indexOf("applewebkit"))this._typeCd=MO.EBrowser.Safari;else{alert("Unknown browser.\n"+a);return}var f=MO.EPlatform.Mobile,g=MO.Console.find(MO.FEnvironmentConsole);MO.Lang.String.contains(a,"android","ipad","iphone","midp","rv:1.2.3.4","windows ce","windows mobile")?(f=MO.EPlatform.Mobile,g.registerValue(MO.EConstant.DeviceType,"mb")):(f=MO.EPlatform.Pc,g.registerValue(MO.EConstant.DeviceType,"pc"));MO.Runtime.setPlatformCd(f);MO.Lang.String.contains(a,
"android 5.1","iphone","ipad")&&(e.soundConfirm=!0);MO.Lang.String.contains(a,"mqqbrowser")&&(e.canvasScale=!1);this._typeCd==MO.EBrowser.Chrome&&MO.Logger.lsnsOutput.register(this,this.onLog);window.applicationCache&&(this._supportHtml5=!0);(f=window.external)&&f.twGetRunPath&&(-1!=a.indexOf("360chrome")||-1!=a.indexOf("360se")?e.soundFinish=!1:-1!=f.twGetRunPath().toLowerCase().indexOf("360se")&&(e.soundFinish=!1));(a=window.devicePixelRatio)&&MO.Runtime.isPlatformMobile()&&(e.pixelRatio=Math.min(a,
3));window.Worker&&(e.optionProcess=!0);window.localStorage&&(e.optionStorage=!0);try{new Blob(["Test"],{type:"text/plain"}),e.blobCreate=!0}catch(h){MO.Logger.warn(this,"Browser blob not support.")}e=window.document;"undefined"!==typeof e.hidden?(b.hidden="hidden",d.visibilitychange="visibilitychange"):"undefined"!==typeof e.mozHidden?(b.hidden="mozHidden",d.visibilitychange="mozvisibilitychange"):"undefined"!==typeof e.msHidden?(b.hidden="msHidden",d.visibilitychange="msvisibilitychange"):"undefined"!==
typeof e.webkitHidden&&(b.hidden="webkitHidden",d.visibilitychange="webkitvisibilitychange");this.refreshOrientation()};MO.RBrowser.prototype.agent=function(){return this._agent};MO.RBrowser.prototype.capability=function(){return this._capability};MO.RBrowser.prototype.defineProperties=function(){return this._defineProperties};MO.RBrowser.prototype.definePropertyGet=function(a){return this._defineProperties[a]};MO.RBrowser.prototype.defineEvents=function(){return this._defineEvents};
MO.RBrowser.prototype.defineEventGet=function(a){return this._defineEvents[a]};MO.RBrowser.prototype.defineMethods=function(){return this._defineMethods};MO.RBrowser.prototype.defineMethodGet=function(a){return this._defineMethods[a]};MO.RBrowser.prototype.supportHtml5=function(){return this._supportHtml5};MO.RBrowser.prototype.hostPath=function(a){return a?this._hostPath+a:this._hostPath};MO.RBrowser.prototype.setHostPath=function(a){this._hostPath=a};
MO.RBrowser.prototype.contentPath=function(a){return a?this._contentPath+a:this._contentPath};MO.RBrowser.prototype.setContentPath=function(a){this._contentPath=a};MO.RBrowser.prototype.typeCd=function(){return this._typeCd};MO.RBrowser.prototype.isBrowser=function(a){return this._typeCd==a};MO.RBrowser.prototype.orientationCd=function(){return this._orientationCd};MO.RBrowser.prototype.setOrientationCd=function(a){this._orientationCd=a};
MO.RBrowser.prototype.isOrientationHorizontal=function(){return this._orientationCd==MO.EOrientation.Horizontal};MO.RBrowser.prototype.isOrientationVertical=function(){return this._orientationCd==MO.EOrientation.Vertical};
MO.RBrowser.prototype.refreshOrientation=function(){if(null!=window.orientation)if(180==window.orientation||0==window.orientation)this._orientationCd=MO.EOrientation.Vertical;else if(90==window.orientation||-90==window.orientation)this._orientationCd=MO.EOrientation.Horizontal;else throw new TError(this,"Unknown orientation mode.");return this._orientationCd};MO.RBrowser.prototype.isVisibility=function(){var a=this.definePropertyGet("hidden");return!window.document[a]};
MO.RBrowser.prototype.encode=function(a){return escape(a)};MO.RBrowser.prototype.decode=function(a){return unescape(a)};MO.RBrowser.prototype.urlEncode=function(a,b){return b?encodeURIComponent(a):encodeURI(a)};MO.RBrowser.prototype.urlDecode=function(a,b){return b?decodeURIComponent(a):decodeURI(a)};
MO.RBrowser.prototype.fullscreen=function(a,b){b?a.requestFullscreen?a.requestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullScreen?a.webkitRequestFullScreen():a.msRequestFullscreen&&a.msRequestFullscreen():a.exitFullscreen?a.exitFullscreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.webkitCancelFullScreen?a.webkitCancelFullScreen():a.msExitFullscreen&&a.msExitFullscreen()};
MO.RBrowser.prototype.downloadBlob=function(a,b){var d=document.createElement("A"),e=document.createEvent("MouseEvents");e.initEvent("click",!0,!1,window,0,0,0,0,0,!1,!1,!1,!1,0,null);d.download=a;d.href=URL.createObjectURL(b);d.dispatchEvent(e)};MO.RBrowser.prototype.downloadText=function(a,b){var d=MO.Labg.Blob.fromText(b);this.downloadBlob(a,d)};MO.RBrowser.prototype.saveConfig=function(a){a.create("Agent").setValue(this._agent)};MO.RBrowser=new MO.RBrowser;MO.Window.Browser=MO.RBrowser;
MO.RXmlUtil=function(){this.httpActiveX=!1;this.httpVendor=null;this.domActiveX=!1;this.domVendor=null;this.construct();return this};
MO.RXmlUtil.prototype.construct=function(){var a=window.document;if(window.ActiveXObject&&!window.XMLHttpRequest)for(var b=["MSXml2.XmlHTTP","Microsoft.XmlHTTP","MSXml.XmlHTTP","MSXml3.XmlHTTP"],d=b.length,e=0;e<d;e++){var f=b[e];try{new ActiveXObject(f);this.httpActiveX=!0;this.httpVendor=f;break}catch(g){m=g}}else if(window.XMLHttpRequest)try{this.httpActiveX=!1}catch(h){m=h}else alert("Unknown http vendor.");if(window.ActiveXObject||!window.DOMParser)for(b=["MSXml2.DOMDocument","Microsoft.XmlDOM",
"MSXml.DOMDocument","MSXml3.XmlDOM"],d=b.length,e=0;e<d;e++){f=b[e];try{new ActiveXObject(f);this.domActiveX=!0;this.domVendor=f;break}catch(k){m=k}}else if(window.DOMParser&&a&&a.implementation&&a.implementation.createDocument)try{document.implementation.createDocument("","",null),this.domActiveX=!1}catch(l){m=l}else alert("Unknown dom vendor.")};MO.RXmlUtil.prototype.isNode=function(a){return RClass.isName(a,"TNode")};
MO.RXmlUtil.prototype.createConnection=function(){var a=null;(a=this.httpActiveX?new ActiveXObject(this.httpVendor):new XMLHttpRequest)||alert("Create xml connection failure. (message="+m+")");return a};MO.RXmlUtil.prototype.createDocument=function(){var a=null;(a=this.domActiveX?new ActiveXObject(this.domVendor):document.implementation.createDocument("","",null))||alert("Create xml document failure. (message="+m+")");return a};
MO.RXmlUtil.prototype.formatText=function(a){null!=a&&(a=a.replace(/\\n/g,"\n"));return a};MO.RXmlUtil.prototype.buildText=function(a,b){if(null!=b){b=b.toString();for(var d=b.length,e=0;e<d;e++){var f=b.charAt(e);switch(f){case "<":a.append("&lt;");break;case ">":a.append("&gt;");break;case "&":a.append("&amp;");break;case "'":a.append("&apos;");break;case '"':a.append("&quot;");break;case "\r":continue;case "\n":a.append("\\n");break;default:a.append(f)}}}return a};
MO.RXmlUtil.prototype.buildNode=function(a,b,d){var e=null,f=d.attributes;if(f){var g=f.length;if(0<g)for(var e=new MO.TAttributes,h=0;h<g;h++){var k=f[h];k.nodeName&&e.set(k.nodeName,this.formatText(k.value))}}g=new MO.TString;g.append(d.value);if(f=d.childNodes)for(k=f.length,h=0;h<k;h++){var l=f[h],p=l.nodeType;p==MO.ENodeType.Text?g.append(l.nodeValue):p==MO.ENodeType.Data&&g.append(l.data)}d=a.create(d.nodeName,e,MO.Lang.String.trim(g.toString()));b?b.push(d):a._root=d;if(f)for(b=f.length,h=
0;h<b;h++)f[h].nodeType==MO.ENodeType.Node&&this.buildNode(a,d,f[h])};MO.RXmlUtil.prototype.makeString=function(a){var b=null;this.domActiveX?(b=new ActiveXObject(this.domVendor),b.async=!1,b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");return b};
MO.RXmlUtil.prototype.makeNode=function(a){if(a.documentElement){var b=new MO.TXmlDocument;this.buildNode(b,null,a.documentElement);return b.root()}if("SCRIPT"==a.tagName){var d=a.textContent;d||(d=a.text);if(d)return b=new MO.TXmlDocument,a=this.makeString(d),this.buildNode(b,null,a.documentElement),b.root()}return null};MO.RXmlUtil.prototype.makeDocument=function(a){var b=new MO.TXmlDocument;a.documentElement&&this.buildNode(b,null,a.documentElement);return b};
MO.RXmlUtil.prototype.unpack=function(a,b){if(MO.Lang.String.isEmpty(a))return null;b||(b=new MO.TNode);var d=new MO.TAttributes;d.unpack(a);b.name=d.get("name");b.value=d.get("value");d.contains("attributes")&&b.attributes().unpack(d.get("attributes"));if(d.contains("nodes")){var e=new MO.TStrings;e.unpack(d.get("nodes"));for(d=0;d<e.count;d++)this.unpack(e.get(d),b.create())}return b};MO.RXml=new MO.RXmlUtil;MO.Window.Xml=MO.RXml;
RJsLoader=new function(){this._callback=null;this.onFinish=RJsLoader_onFinish;this.onLoad=RJsLoader_onLoad;this.loadUrl=RJsLoader_loadUrl;return this};function RJsLoader_onFinish(a){a=MO.Lang.String.decodeUtf(a);eval(a);top.MO=MO;RJsLoader._callback()}function RJsLoader_onLoad(a){a=a.content;if(a.constructor!=ArrayBuffer)return alert("Load script failure.");(new LZMA("../ajs/lzma_worker.js")).decompress(new Uint8Array(a),this.onFinish,null)}
function RJsLoader_loadUrl(a,b){var d=MO.Class.create(MO.FHttpConnection);d.setAsynchronous(!0);d.addLoadListener(this,this.onLoad);d.send(a);this._callback=b};
