DROP TABLE IF EXISTS `DT_RES_SCENE_THEME`;

DROP TABLE IF EXISTS `DT_RES_TEMPLATE_MATERIAL_GROUP`;
DROP TABLE IF EXISTS `DT_RES_TEMPLATE_THEME`;

DROP TABLE IF EXISTS `DT_RES_MATERIAL_GROUP`;
DROP TABLE IF EXISTS `DT_RES_THEME`;

DROP TABLE IF EXISTS `DT_RES_MODEL_ANIMATION`;
DROP TABLE IF EXISTS `DT_RES_MODEL_SKELETON`;

DROP TABLE IF EXISTS `DT_RES_MESH_TRACK`;
DROP TABLE IF EXISTS `DT_RES_MESH_SKIN`;
DROP TABLE IF EXISTS `DT_RES_MESH_STREAM`;
DROP TABLE IF EXISTS `DT_RES_MESH`;

DROP TABLE IF EXISTS `DT_RES_SKELETON_ANIMATION`;
DROP TABLE IF EXISTS `DT_RES_SKELETON_SKIN_STREAM`;
DROP TABLE IF EXISTS `DT_RES_SKELETON_SKIN`;
DROP TABLE IF EXISTS `DT_RES_SKELETON`;

DROP TABLE IF EXISTS `DT_RES_ANIMATION_ACTION`;
DROP TABLE IF EXISTS `DT_RES_ANIMATION_TRACK`;
DROP TABLE IF EXISTS `DT_RES_ANIMATION`;

DROP TABLE IF EXISTS `DT_RES_TRACK`;
DROP TABLE IF EXISTS `DT_RES_STREAM`;



DROP TABLE IF EXISTS `DT_RES_SCENE`;

DROP TABLE IF EXISTS `DT_RES_TEMPLATE`;

DROP TABLE IF EXISTS `DT_RES_MODEL_MESH_TRACK`;
DROP TABLE IF EXISTS `DT_RES_MODEL_MESH_STREAM`;
DROP TABLE IF EXISTS `DT_RES_MODEL_MESH`;
DROP TABLE IF EXISTS `DT_RES_MODEL`;

DROP TABLE IF EXISTS `DT_RES_MATERIAL_BITMAP`;
DROP TABLE IF EXISTS `DT_RES_MATERIAL`;
DROP TABLE IF EXISTS `DT_RES_BITMAP`;

DROP TABLE IF EXISTS `DT_RES_RESOURCE`;
DROP TABLE IF EXISTS `DT_RES_CATALOG`;
DROP TABLE IF EXISTS `DT_RES_TYPE`;

DROP TABLE IF EXISTS `DT_SOL_PROJECT`;

DROP TABLE IF EXISTS `DT_PSN_USER`;
