DROP TABLE IF EXISTS `DT_RES_SCENE`;

DROP TABLE IF EXISTS `DT_RES_TEMPLATE`;

DROP TABLE IF EXISTS `DT_RES_MODEL_MESH_TRACK`;
DROP TABLE IF EXISTS `DT_RES_MODEL_MESH_STREAM`;
DROP TABLE IF EXISTS `DT_RES_MODEL_MESH`;
DROP TABLE IF EXISTS `DT_RES_MODEL`;

DROP TABLE IF EXISTS `DT_RES_MATERIAL_BITMAP`;
DROP TABLE IF EXISTS `DT_RES_MATERIAL`;
DROP TABLE IF EXISTS `DT_RES_BITMAP`;

DROP TABLE IF EXISTS `DT_RES_RESOURCE`;
DROP TABLE IF EXISTS `DT_RES_CATALOG`;
DROP TABLE IF EXISTS `DT_RES_TYPE`;

DROP TABLE IF EXISTS `DT_SOL_PROJECT`;

DROP TABLE IF EXISTS `DT_PSN_USER`;
